// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes a BigQuery table.
public struct BigQueryTableSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The table source type.
  public var tableSourceType: TableSourceType = TableSourceType()

  /// Output only.
  public var typeSpec: OneOf_TypeSpec? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BigQueryTableSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryTableSpec().with { $0.tableSourceType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tableSourceType = CodingKeys(stringValue: "tableSourceType")
    static let viewSpec = CodingKeys(stringValue: "viewSpec")
    static let tableSpec = CodingKeys(stringValue: "tableSpec")

    static let _knownKeys: Set<Swift.String> = [
      "tableSourceType",
      "viewSpec",
      "tableSpec",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(TableSourceType.self, forKey: .tableSourceType) {
      self.tableSourceType = value
    }

    var typeSpec: OneOf_TypeSpec? = nil
    let typeSpecCheckAndSet = {
      if typeSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'typeSpec'"))
      }
      typeSpec = $0
    }
    if let viewSpec = try container.decodeIfPresent(ViewSpec?.self, forKey: .viewSpec) {
      try typeSpecCheckAndSet(.viewSpec(viewSpec))
    }
    if let tableSpec = try container.decodeIfPresent(TableSpec?.self, forKey: .tableSpec) {
      try typeSpecCheckAndSet(.tableSpec(tableSpec))
    }
    self.typeSpec = typeSpec
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.tableSourceType, forKey: .tableSourceType)

    if let choice = self.typeSpec {
      switch choice {
      case .viewSpec(let value):
        try container.encode(value, forKey: .viewSpec)
      case .tableSpec(let value):
        try container.encode(value, forKey: .tableSpec)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Output only.
  public enum OneOf_TypeSpec: Codable, Equatable, Sendable {
    /// Table view specification. Populated only if
    /// the `table_source_type` is `BIGQUERY_VIEW`.
    indirect case viewSpec(ViewSpec?)
    /// Specification of a BigQuery table. Populated only if
    /// the `table_source_type` is `BIGQUERY_TABLE`.
    indirect case tableSpec(TableSpec?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.BigQueryTableSpec"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
