// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specification that applies to a dataset. Valid only for
/// entries with the `DATASET` type.
public struct DatasetSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Fields specific to the source system.
  public var systemSpec: OneOf_SystemSpec? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DatasetSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatasetSpec().with { $0.vertexDatasetSpec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vertexDatasetSpec = CodingKeys(stringValue: "vertexDatasetSpec")

    static let _knownKeys: Set<Swift.String> = [
      "vertexDatasetSpec"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var systemSpec: OneOf_SystemSpec? = nil
    let systemSpecCheckAndSet = {
      if systemSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'systemSpec'"))
      }
      systemSpec = $0
    }
    if let vertexDatasetSpec = try container.decodeIfPresent(
      VertexDatasetSpec?.self, forKey: .vertexDatasetSpec)
    {
      try systemSpecCheckAndSet(.vertexDatasetSpec(vertexDatasetSpec))
    }
    self.systemSpec = systemSpec
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.systemSpec {
      switch choice {
      case .vertexDatasetSpec(let value):
        try container.encode(value, forKey: .vertexDatasetSpec)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Fields specific to the source system.
  public enum OneOf_SystemSpec: Codable, Equatable, Sendable {
    /// Vertex AI Dataset specific fields
    indirect case vertexDatasetSpec(VertexDatasetSpec?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.DatasetSpec"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
