// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specification that applies to a table resource. Valid only
/// for entries with the `TABLE` type.
public struct DatabaseTableSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Type of this table.
  public var type: DatabaseTableSpec.TableType = DatabaseTableSpec.TableType()

  /// Output only. Fields specific to a Dataplex table and present only in the
  /// Dataplex table entries.
  public var dataplexTable: DataplexTableSpec? = nil

  /// Spec what applies to tables that are actually views.
  /// Not set for "real" tables.
  public var databaseViewSpec: DatabaseTableSpec.DatabaseViewSpec? = nil

  /// Initialize a new instance of `DatabaseTableSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatabaseTableSpec().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specification that applies to database view.
  public struct DatabaseViewSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Type of this view.
    public var viewType: DatabaseTableSpec.DatabaseViewSpec.ViewType = DatabaseTableSpec
      .DatabaseViewSpec.ViewType()

    /// Definition of the view.
    public var sourceDefinition: OneOf_SourceDefinition? = nil

    /// Initialize a new instance of `DatabaseViewSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DatabaseViewSpec().with { $0.viewType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case viewType = "viewType"
      case baseTable = "baseTable"
      case sqlQuery = "sqlQuery"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.viewType = try container.decode(
        DatabaseTableSpec.DatabaseViewSpec.ViewType.self, forKey: .viewType)

      var sourceDefinition: OneOf_SourceDefinition? = nil
      let sourceDefinitionCheckAndSet = {
        if sourceDefinition != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'sourceDefinition'"))
        }
        sourceDefinition = $0
      }
      if let baseTable = try container.decodeIfPresent(Swift.String.self, forKey: .baseTable) {
        try sourceDefinitionCheckAndSet(.baseTable(baseTable))
      }
      if let sqlQuery = try container.decodeIfPresent(Swift.String.self, forKey: .sqlQuery) {
        try sourceDefinitionCheckAndSet(.sqlQuery(sqlQuery))
      }
      self.sourceDefinition = sourceDefinition
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.viewType, forKey: .viewType)

      if let choice = self.sourceDefinition {
        switch choice {
        case .baseTable(let value):
          try container.encode(value, forKey: .baseTable)
        case .sqlQuery(let value):
          try container.encode(value, forKey: .sqlQuery)
        }
      }
    }

    /// Concrete type of the view.
    public enum ViewType: Codable, Equatable, Sendable {
      /// Default unknown view type.
      case unspecified
      /// Standard view.
      case standardView
      /// Materialized view.
      case materializedView
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .standardView: return 1
        case .materializedView: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "VIEW_TYPE_UNSPECIFIED"
        case .standardView: return "STANDARD_VIEW"
        case .materializedView: return "MATERIALIZED_VIEW"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ViewType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "VIEW_TYPE_UNSPECIFIED": self = .unspecified
        case "STANDARD_VIEW": self = .standardView
        case "MATERIALIZED_VIEW": self = .materializedView
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ViewType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .standardView
        case 2: self = .materializedView
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .standardView: return try container.encode(1)
        case .materializedView: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Definition of the view.
    public enum OneOf_SourceDefinition: Codable, Equatable, Sendable {
      /// Name of a singular table this view reflects one to one.
      case baseTable(Swift.String)
      /// SQL query used to generate this view.
      case sqlQuery(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.DatabaseTableSpec.DatabaseViewSpec"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Type of the table.
  public enum TableType: Codable, Equatable, Sendable {
    /// Default unknown table type.
    case unspecified
    /// Native table.
    case native
    /// External table.
    case external
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .native: return 1
      case .external: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TABLE_TYPE_UNSPECIFIED"
      case .native: return "NATIVE"
      case .external: return "EXTERNAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TableType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TABLE_TYPE_UNSPECIFIED": self = .unspecified
      case "NATIVE": self = .native
      case "EXTERNAL": self = .external
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TableType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .native
      case 2: self = .external
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .native: return try container.encode(1)
      case .external: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.DatabaseTableSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
