// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class DataCatalogLogging: DataCatalogStub {
    let inner: any DataCatalogStub
    let logger: Logger

    public init(_ inner: any DataCatalogStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-datacatalog-v1"
      logger[metadataKey: "gcp.client.service"] = "datacatalog"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DataCatalog"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func searchCatalog(
      request: SearchCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.SearchCatalogResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchCatalog",
        action: {
          (r: SearchCatalogRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.SearchCatalogResponse
          in
          return try await self.inner.searchCatalog(request: r, options: o)
        })
    }

    public func createEntryGroup(
      request: CreateEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.EntryGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEntryGroup",
        action: {
          (r: CreateEntryGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.EntryGroup
          in
          return try await self.inner.createEntryGroup(request: r, options: o)
        })
    }

    public func getEntryGroup(
      request: GetEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.EntryGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEntryGroup",
        action: {
          (r: GetEntryGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.EntryGroup
          in
          return try await self.inner.getEntryGroup(request: r, options: o)
        })
    }

    public func updateEntryGroup(
      request: UpdateEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.EntryGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEntryGroup",
        action: {
          (r: UpdateEntryGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.EntryGroup
          in
          return try await self.inner.updateEntryGroup(request: r, options: o)
        })
    }

    public func deleteEntryGroup(
      request: DeleteEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEntryGroup",
        action: { (r: DeleteEntryGroupRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteEntryGroup(request: r, options: o)
        })
    }

    public func listEntryGroups(
      request: ListEntryGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ListEntryGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEntryGroups",
        action: {
          (r: ListEntryGroupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.ListEntryGroupsResponse
          in
          return try await self.inner.listEntryGroups(request: r, options: o)
        })
    }

    public func createEntry(
      request: CreateEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Entry {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEntry",
        action: {
          (r: CreateEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Entry
          in
          return try await self.inner.createEntry(request: r, options: o)
        })
    }

    public func updateEntry(
      request: UpdateEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Entry {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEntry",
        action: {
          (r: UpdateEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Entry
          in
          return try await self.inner.updateEntry(request: r, options: o)
        })
    }

    public func deleteEntry(
      request: DeleteEntryRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEntry",
        action: { (r: DeleteEntryRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteEntry(request: r, options: o)
        })
    }

    public func getEntry(
      request: GetEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Entry {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEntry",
        action: {
          (r: GetEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Entry
          in
          return try await self.inner.getEntry(request: r, options: o)
        })
    }

    public func lookupEntry(
      request: LookupEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Entry {
      try await self._intercept(
        request: request,
        options: options,
        name: "lookupEntry",
        action: {
          (r: LookupEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Entry
          in
          return try await self.inner.lookupEntry(request: r, options: o)
        })
    }

    public func listEntries(
      request: ListEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ListEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEntries",
        action: {
          (r: ListEntriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.ListEntriesResponse
          in
          return try await self.inner.listEntries(request: r, options: o)
        })
    }

    public func modifyEntryOverview(
      request: ModifyEntryOverviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.EntryOverview {
      try await self._intercept(
        request: request,
        options: options,
        name: "modifyEntryOverview",
        action: {
          (r: ModifyEntryOverviewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.EntryOverview
          in
          return try await self.inner.modifyEntryOverview(request: r, options: o)
        })
    }

    public func modifyEntryContacts(
      request: ModifyEntryContactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Contacts {
      try await self._intercept(
        request: request,
        options: options,
        name: "modifyEntryContacts",
        action: {
          (r: ModifyEntryContactsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Contacts
          in
          return try await self.inner.modifyEntryContacts(request: r, options: o)
        })
    }

    public func createTagTemplate(
      request: CreateTagTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTagTemplate",
        action: {
          (r: CreateTagTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplate
          in
          return try await self.inner.createTagTemplate(request: r, options: o)
        })
    }

    public func getTagTemplate(
      request: GetTagTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTagTemplate",
        action: {
          (r: GetTagTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplate
          in
          return try await self.inner.getTagTemplate(request: r, options: o)
        })
    }

    public func updateTagTemplate(
      request: UpdateTagTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTagTemplate",
        action: {
          (r: UpdateTagTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplate
          in
          return try await self.inner.updateTagTemplate(request: r, options: o)
        })
    }

    public func deleteTagTemplate(
      request: DeleteTagTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTagTemplate",
        action: { (r: DeleteTagTemplateRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTagTemplate(request: r, options: o)
        })
    }

    public func createTagTemplateField(
      request: CreateTagTemplateFieldRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplateField {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTagTemplateField",
        action: {
          (r: CreateTagTemplateFieldRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplateField
          in
          return try await self.inner.createTagTemplateField(request: r, options: o)
        })
    }

    public func updateTagTemplateField(
      request: UpdateTagTemplateFieldRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplateField {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTagTemplateField",
        action: {
          (r: UpdateTagTemplateFieldRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplateField
          in
          return try await self.inner.updateTagTemplateField(request: r, options: o)
        })
    }

    public func renameTagTemplateField(
      request: RenameTagTemplateFieldRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplateField {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameTagTemplateField",
        action: {
          (r: RenameTagTemplateFieldRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplateField
          in
          return try await self.inner.renameTagTemplateField(request: r, options: o)
        })
    }

    public func renameTagTemplateFieldEnumValue(
      request: RenameTagTemplateFieldEnumValueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.TagTemplateField {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameTagTemplateFieldEnumValue",
        action: {
          (r: RenameTagTemplateFieldEnumValueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.TagTemplateField
          in
          return try await self.inner.renameTagTemplateFieldEnumValue(request: r, options: o)
        })
    }

    public func deleteTagTemplateField(
      request: DeleteTagTemplateFieldRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTagTemplateField",
        action: {
          (r: DeleteTagTemplateFieldRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTagTemplateField(request: r, options: o)
        })
    }

    public func createTag(
      request: CreateTagRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Tag {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTag",
        action: {
          (r: CreateTagRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Tag
          in
          return try await self.inner.createTag(request: r, options: o)
        })
    }

    public func updateTag(
      request: UpdateTagRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Tag {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTag",
        action: {
          (r: UpdateTagRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Tag
          in
          return try await self.inner.updateTag(request: r, options: o)
        })
    }

    public func deleteTag(
      request: DeleteTagRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTag",
        action: { (r: DeleteTagRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTag(request: r, options: o)
        })
    }

    public func listTags(
      request: ListTagsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ListTagsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTags",
        action: {
          (r: ListTagsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.ListTagsResponse
          in
          return try await self.inner.listTags(request: r, options: o)
        })
    }

    public func reconcileTags(
      request: ReconcileTagsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "reconcileTags",
        action: {
          (r: ReconcileTagsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.reconcileTags(request: r, options: o)
        })
    }

    public func starEntry(
      request: StarEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.StarEntryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "starEntry",
        action: {
          (r: StarEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.StarEntryResponse
          in
          return try await self.inner.starEntry(request: r, options: o)
        })
    }

    public func unstarEntry(
      request: UnstarEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.UnstarEntryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "unstarEntry",
        action: {
          (r: UnstarEntryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.UnstarEntryResponse
          in
          return try await self.inner.unstarEntry(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func importEntries(
      request: ImportEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importEntries",
        action: {
          (r: ImportEntriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importEntries(request: r, options: o)
        })
    }

    public func setConfig(
      request: SetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.MigrationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "setConfig",
        action: {
          (r: SetConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.MigrationConfig
          in
          return try await self.inner.setConfig(request: r, options: o)
        })
    }

    public func retrieveConfig(
      request: RetrieveConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.OrganizationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "retrieveConfig",
        action: {
          (r: RetrieveConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.OrganizationConfig
          in
          return try await self.inner.retrieveConfig(request: r, options: o)
        })
    }

    public func retrieveEffectiveConfig(
      request: RetrieveEffectiveConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.MigrationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "retrieveEffectiveConfig",
        action: {
          (r: RetrieveEffectiveConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.MigrationConfig
          in
          return try await self.inner.retrieveEffectiveConfig(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
