// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Physical location of an entry.
public struct DataSource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Service that physically stores the data.
  public var service: DataSource.Service = DataSource.Service()

  /// Full name of a resource as defined by the service. For example:
  ///
  /// `//bigquery.googleapis.com/projects/{PROJECT_ID}/locations/{LOCATION}/datasets/{DATASET_ID}/tables/{TABLE_ID}`
  public var resource: Swift.String = Swift.String()

  /// Output only. Data Catalog entry name, if applicable.
  public var sourceEntry: Swift.String = Swift.String()

  public var properties: OneOf_Properties? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSource().with { $0.service = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let service = CodingKeys(stringValue: "service")
    static let resource = CodingKeys(stringValue: "resource")
    static let sourceEntry = CodingKeys(stringValue: "sourceEntry")
    static let storageProperties = CodingKeys(stringValue: "storageProperties")

    static let _knownKeys: Set<Swift.String> = [
      "service",
      "resource",
      "sourceEntry",
      "storageProperties",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(DataSource.Service.self, forKey: .service) {
      self.service = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
      self.resource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceEntry) {
      self.sourceEntry = value
    }

    var properties: OneOf_Properties? = nil
    let propertiesCheckAndSet = {
      if properties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'properties'"))
      }
      properties = $0
    }
    if let storageProperties = try container.decodeIfPresent(
      StorageProperties?.self, forKey: .storageProperties)
    {
      try propertiesCheckAndSet(.storageProperties(storageProperties))
    }
    self.properties = properties
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.service, forKey: .service)
    try container.encode(self.resource, forKey: .resource)
    try container.encode(self.sourceEntry, forKey: .sourceEntry)

    if let choice = self.properties {
      switch choice {
      case .storageProperties(let value):
        try container.encode(value, forKey: .storageProperties)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Name of a service that stores the data.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Service: Codable, Equatable, Sendable {
    /// Default unknown service.
    case unspecified
    /// Google Cloud Storage service.
    case cloudStorage
    /// BigQuery service.
    case bigquery
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudStorage: return 1
      case .bigquery: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SERVICE_UNSPECIFIED"
      case .cloudStorage: return "CLOUD_STORAGE"
      case .bigquery: return "BIGQUERY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Service/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SERVICE_UNSPECIFIED": self = .unspecified
      case "CLOUD_STORAGE": self = .cloudStorage
      case "BIGQUERY": self = .bigquery
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Service/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudStorage
      case 2: self = .bigquery
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SERVICE_UNSPECIFIED")
      case .cloudStorage: return try container.encode("CLOUD_STORAGE")
      case .bigquery: return try container.encode("BIGQUERY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_Properties: Codable, Equatable, Sendable {
    /// Detailed properties of the underlying storage.
    indirect case storageProperties(StorageProperties?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.DataSource"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
