// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Specification that applies to a dataset. Valid only for
/// entries with the `DATASET` type.
public struct DatasetSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Fields specific to the source system.
  public var systemSpec: OneOf_SystemSpec? = nil

  /// Initialize a new instance of `DatasetSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatasetSpec().with { $0.vertexDatasetSpec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case vertexDatasetSpec = "vertexDatasetSpec"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var systemSpec: OneOf_SystemSpec? = nil
    let systemSpecCheckAndSet = {
      if systemSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'systemSpec'"))
      }
      systemSpec = $0
    }
    if let vertexDatasetSpec = try container.decodeIfPresent(
      VertexDatasetSpec?.self, forKey: .vertexDatasetSpec)
    {
      try systemSpecCheckAndSet(.vertexDatasetSpec(vertexDatasetSpec))
    }
    self.systemSpec = systemSpec
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.systemSpec {
      switch choice {
      case .vertexDatasetSpec(let value):
        try container.encode(value, forKey: .vertexDatasetSpec)
      }
    }
  }

  /// Fields specific to the source system.
  public enum OneOf_SystemSpec: Codable, Equatable, Sendable {
    /// Vertex AI Dataset specific fields
    indirect case vertexDatasetSpec(VertexDatasetSpec?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.DatasetSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
