// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Common Dataplex fields.
public struct DataplexSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Fully qualified resource name of an asset in Dataplex, to which the
  /// underlying data source (Cloud Storage bucket or BigQuery dataset) of the
  /// entity is attached.
  public var asset: Swift.String = Swift.String()

  /// Format of the data.
  public var dataFormat: PhysicalSchema? = nil

  /// Compression format of the data, e.g., zip, gzip etc.
  public var compressionFormat: Swift.String = Swift.String()

  /// Project ID of the underlying Cloud Storage or BigQuery data. Note that
  /// this may not be the same project as the correspondingly Dataplex lake /
  /// zone / asset.
  public var projectId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataplexSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataplexSpec().with { $0.asset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let asset = CodingKeys(stringValue: "asset")
    static let dataFormat = CodingKeys(stringValue: "dataFormat")
    static let compressionFormat = CodingKeys(stringValue: "compressionFormat")
    static let projectId = CodingKeys(stringValue: "projectId")

    static let _knownKeys: Set<Swift.String> = [
      "asset",
      "dataFormat",
      "compressionFormat",
      "projectId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .asset) {
      self.asset = value
    }
    self.dataFormat = try container.decodeIfPresent(PhysicalSchema.self, forKey: .dataFormat)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .compressionFormat) {
      self.compressionFormat = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.asset, forKey: .asset)
    try container.encodeIfPresent(self.dataFormat, forKey: .dataFormat)
    try container.encode(self.compressionFormat, forKey: .compressionFormat)
    try container.encode(self.projectId, forKey: .projectId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.DataplexSpec"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
