// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// External table registered by Dataplex.
/// Dataplex publishes data discovered from an asset into multiple other systems
/// (BigQuery, DPMS) in form of tables. We call them "external tables". External
/// tables are also synced into the Data Catalog.
/// This message contains pointers to
/// those external tables (fully qualified name, resource name et cetera) within
/// the Data Catalog.
public struct DataplexExternalTable: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Service in which the external table is registered.
  public var system: IntegratedSystem = IntegratedSystem()

  /// Fully qualified name (FQN) of the external table.
  public var fullyQualifiedName: Swift.String = Swift.String()

  /// Google Cloud resource name of the external table.
  public var googleCloudResource: Swift.String = Swift.String()

  /// Name of the Data Catalog entry representing the external table.
  public var dataCatalogEntry: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataplexExternalTable`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataplexExternalTable().with { $0.system = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let system = CodingKeys(stringValue: "system")
    static let fullyQualifiedName = CodingKeys(stringValue: "fullyQualifiedName")
    static let googleCloudResource = CodingKeys(stringValue: "googleCloudResource")
    static let dataCatalogEntry = CodingKeys(stringValue: "dataCatalogEntry")

    static let _knownKeys: Set<Swift.String> = [
      "system",
      "fullyQualifiedName",
      "googleCloudResource",
      "dataCatalogEntry",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(IntegratedSystem.self, forKey: .system) {
      self.system = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullyQualifiedName) {
      self.fullyQualifiedName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .googleCloudResource) {
      self.googleCloudResource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataCatalogEntry) {
      self.dataCatalogEntry = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.system, forKey: .system)
    try container.encode(self.fullyQualifiedName, forKey: .fullyQualifiedName)
    try container.encode(self.googleCloudResource, forKey: .googleCloudResource)
    try container.encode(self.dataCatalogEntry, forKey: .dataCatalogEntry)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.DataplexExternalTable"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
