// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Entry group metadata.
///
///  An `EntryGroup` resource represents a logical grouping of zero or more
///  Data Catalog [Entry][google.cloud.datacatalog.v1.Entry] resources.
///
/// [google.cloud.datacatalog.v1.Entry]: <doc:Entry>
public struct EntryGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the entry group in URL format.
  ///
  /// Note: The entry group itself and its child resources might not be
  /// stored in the location specified in its name.
  public var name: Swift.String = Swift.String()

  /// A short name to identify the entry group, for example,
  /// "analytics data - jan 2011". Default value is an empty string.
  public var displayName: Swift.String = Swift.String()

  /// Entry group description. Can consist of several sentences or
  /// paragraphs that describe the entry group contents.
  /// Default value is an empty string.
  public var description: Swift.String = Swift.String()

  /// Output only. Timestamps of the entry group. Default value is empty.
  public var dataCatalogTimestamps: SystemTimestamps? = nil

  /// Optional. When set to [true], it means DataCatalog EntryGroup was
  /// transferred to Dataplex Catalog Service. It makes EntryGroup and its
  /// Entries to be read-only in DataCatalog. However, new Tags on EntryGroup and
  /// its Entries can be created. After setting the flag to [true] it cannot be
  /// unset.
  public var transferredToDataplex: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `EntryGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntryGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.EntryGroup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
