// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Entry metadata.
/// A Data Catalog entry represents another resource in Google
/// Cloud Platform (such as a BigQuery dataset or a Pub/Sub topic) or
/// outside of it. You can use the `linked_resource` field
/// in the entry resource to refer to the original resource ID of the source
/// system.
///
/// An entry resource contains resource details, for example, its schema.
/// Additionally, you can attach flexible metadata to an entry in the form of a
/// [Tag][google.cloud.datacatalog.v1.Tag].
///
/// [google.cloud.datacatalog.v1.Tag]: <doc:Tag>
public struct Entry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of an entry in URL format.
  ///
  /// Note: The entry itself and its child resources might not be
  /// stored in the location specified in its name.
  public var name: Swift.String = Swift.String()

  /// The resource this metadata entry refers to.
  ///
  /// For Google Cloud Platform resources, `linked_resource` is the
  /// [Full Resource Name]
  /// (https://cloud.google.com/apis/design/resource_names#full_resource_name).
  /// For example, the `linked_resource` for a table resource from BigQuery is:
  ///
  /// `//bigquery.googleapis.com/projects/{PROJECT_ID}/datasets/{DATASET_ID}/tables/{TABLE_ID}`
  ///
  /// Output only when the entry is one of the types in the `EntryType` enum.
  ///
  /// For entries with a `user_specified_type`, this field is optional and
  /// defaults to an empty string.
  ///
  /// The resource string must contain only letters (a-z, A-Z), numbers (0-9),
  /// underscores (_), periods (.), colons (:), slashes (/), dashes (-),
  /// and hashes (#).
  /// The maximum size is 200 bytes when encoded in UTF-8.
  public var linkedResource: Swift.String = Swift.String()

  /// [Fully Qualified Name
  /// (FQN)](https://cloud.google.com//data-catalog/docs/fully-qualified-names)
  /// of the resource. Set automatically for entries representing resources from
  /// synced systems. Settable only during creation, and read-only later. Can
  /// be used for search and lookup of the entries.
  ///
  public var fullyQualifiedName: Swift.String = Swift.String()

  /// Display name of an entry.
  ///
  /// The maximum size is 500 bytes when encoded in UTF-8.
  /// Default value is an empty string.
  public var displayName: Swift.String = Swift.String()

  /// Entry description that can consist of several sentences or paragraphs
  /// that describe entry contents.
  ///
  /// The description must not contain Unicode non-characters as well as C0
  /// and C1 control codes except tabs (HT), new lines (LF), carriage returns
  /// (CR), and page breaks (FF).
  /// The maximum size is 2000 bytes when encoded in UTF-8.
  /// Default value is an empty string.
  public var description: Swift.String = Swift.String()

  /// Business Context of the entry. Not supported for BigQuery datasets
  public var businessContext: BusinessContext? = nil

  /// Schema of the entry. An entry might not have any schema attached to it.
  public var schema: Schema? = nil

  /// Timestamps from the underlying resource, not from the Data Catalog
  /// entry.
  ///
  /// Output only when the entry has a system listed in the `IntegratedSystem`
  /// enum. For entries with `user_specified_system`, this field is optional
  /// and defaults to an empty timestamp.
  public var sourceSystemTimestamps: SystemTimestamps? = nil

  /// Resource usage statistics.
  public var usageSignal: UsageSignal? = nil

  /// Cloud labels attached to the entry.
  ///
  /// In Data Catalog, you can create and modify labels attached only to custom
  /// entries. Synced entries have unmodifiable labels that come from the source
  /// system.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Physical location of the entry.
  public var dataSource: DataSource? = nil

  /// Output only. Additional information related to the entry. Private to the
  /// current user.
  public var personalDetails: PersonalDetails? = nil

  /// Required. Entry type.
  public var entryType: OneOf_EntryType? = nil

  /// The source system of the entry.
  public var system: OneOf_System? = nil

  /// System specification.
  /// Can be used as a complement for `spec`, when some metadata is relevant for
  /// all entries existing within given system
  public var systemSpec: OneOf_SystemSpec? = nil

  /// Type specification.
  public var typeSpec: OneOf_TypeSpec? = nil

  /// Type- and system-specific information. Specifications for types contain
  /// fields common to all entries of a given type, and sub-specifications with
  /// fields specific to a given source system.
  ///
  /// When extending the API with new types and systems, use this field instead
  /// of the legacy `type_spec`.
  public var spec: OneOf_Spec? = nil

  /// Initialize a new instance of `Entry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Entry().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case linkedResource = "linkedResource"
    case fullyQualifiedName = "fullyQualifiedName"
    case type = "type"
    case userSpecifiedType = "userSpecifiedType"
    case integratedSystem = "integratedSystem"
    case userSpecifiedSystem = "userSpecifiedSystem"
    case sqlDatabaseSystemSpec = "sqlDatabaseSystemSpec"
    case lookerSystemSpec = "lookerSystemSpec"
    case cloudBigtableSystemSpec = "cloudBigtableSystemSpec"
    case gcsFilesetSpec = "gcsFilesetSpec"
    case bigqueryTableSpec = "bigqueryTableSpec"
    case bigqueryDateShardedSpec = "bigqueryDateShardedSpec"
    case databaseTableSpec = "databaseTableSpec"
    case dataSourceConnectionSpec = "dataSourceConnectionSpec"
    case routineSpec = "routineSpec"
    case datasetSpec = "datasetSpec"
    case filesetSpec = "filesetSpec"
    case serviceSpec = "serviceSpec"
    case modelSpec = "modelSpec"
    case featureOnlineStoreSpec = "featureOnlineStoreSpec"
    case displayName = "displayName"
    case description = "description"
    case businessContext = "businessContext"
    case schema = "schema"
    case sourceSystemTimestamps = "sourceSystemTimestamps"
    case usageSignal = "usageSignal"
    case labels = "labels"
    case dataSource = "dataSource"
    case personalDetails = "personalDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.linkedResource = try container.decode(Swift.String.self, forKey: .linkedResource)
    self.fullyQualifiedName = try container.decode(Swift.String.self, forKey: .fullyQualifiedName)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.businessContext = try container.decodeIfPresent(
      BusinessContext.self, forKey: .businessContext)
    self.schema = try container.decodeIfPresent(Schema.self, forKey: .schema)
    self.sourceSystemTimestamps = try container.decodeIfPresent(
      SystemTimestamps.self, forKey: .sourceSystemTimestamps)
    self.usageSignal = try container.decodeIfPresent(UsageSignal.self, forKey: .usageSignal)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.dataSource = try container.decodeIfPresent(DataSource.self, forKey: .dataSource)
    self.personalDetails = try container.decodeIfPresent(
      PersonalDetails.self, forKey: .personalDetails)

    var entryType: OneOf_EntryType? = nil
    let entryTypeCheckAndSet = {
      if entryType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'entryType'"))
      }
      entryType = $0
    }
    if let type = try container.decodeIfPresent(EntryType.self, forKey: .type) {
      try entryTypeCheckAndSet(.type(type))
    }
    if let userSpecifiedType = try container.decodeIfPresent(
      Swift.String.self, forKey: .userSpecifiedType)
    {
      try entryTypeCheckAndSet(.userSpecifiedType(userSpecifiedType))
    }
    self.entryType = entryType

    var system: OneOf_System? = nil
    let systemCheckAndSet = {
      if system != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'system'"))
      }
      system = $0
    }
    if let integratedSystem = try container.decodeIfPresent(
      IntegratedSystem.self, forKey: .integratedSystem)
    {
      try systemCheckAndSet(.integratedSystem(integratedSystem))
    }
    if let userSpecifiedSystem = try container.decodeIfPresent(
      Swift.String.self, forKey: .userSpecifiedSystem)
    {
      try systemCheckAndSet(.userSpecifiedSystem(userSpecifiedSystem))
    }
    self.system = system

    var systemSpec: OneOf_SystemSpec? = nil
    let systemSpecCheckAndSet = {
      if systemSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'systemSpec'"))
      }
      systemSpec = $0
    }
    if let sqlDatabaseSystemSpec = try container.decodeIfPresent(
      SqlDatabaseSystemSpec?.self, forKey: .sqlDatabaseSystemSpec)
    {
      try systemSpecCheckAndSet(.sqlDatabaseSystemSpec(sqlDatabaseSystemSpec))
    }
    if let lookerSystemSpec = try container.decodeIfPresent(
      LookerSystemSpec?.self, forKey: .lookerSystemSpec)
    {
      try systemSpecCheckAndSet(.lookerSystemSpec(lookerSystemSpec))
    }
    if let cloudBigtableSystemSpec = try container.decodeIfPresent(
      CloudBigtableSystemSpec?.self, forKey: .cloudBigtableSystemSpec)
    {
      try systemSpecCheckAndSet(.cloudBigtableSystemSpec(cloudBigtableSystemSpec))
    }
    self.systemSpec = systemSpec

    var typeSpec: OneOf_TypeSpec? = nil
    let typeSpecCheckAndSet = {
      if typeSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'typeSpec'"))
      }
      typeSpec = $0
    }
    if let gcsFilesetSpec = try container.decodeIfPresent(
      GcsFilesetSpec?.self, forKey: .gcsFilesetSpec)
    {
      try typeSpecCheckAndSet(.gcsFilesetSpec(gcsFilesetSpec))
    }
    if let bigqueryTableSpec = try container.decodeIfPresent(
      BigQueryTableSpec?.self, forKey: .bigqueryTableSpec)
    {
      try typeSpecCheckAndSet(.bigqueryTableSpec(bigqueryTableSpec))
    }
    if let bigqueryDateShardedSpec = try container.decodeIfPresent(
      BigQueryDateShardedSpec?.self, forKey: .bigqueryDateShardedSpec)
    {
      try typeSpecCheckAndSet(.bigqueryDateShardedSpec(bigqueryDateShardedSpec))
    }
    self.typeSpec = typeSpec

    var spec: OneOf_Spec? = nil
    let specCheckAndSet = {
      if spec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'spec'"
          ))
      }
      spec = $0
    }
    if let databaseTableSpec = try container.decodeIfPresent(
      DatabaseTableSpec?.self, forKey: .databaseTableSpec)
    {
      try specCheckAndSet(.databaseTableSpec(databaseTableSpec))
    }
    if let dataSourceConnectionSpec = try container.decodeIfPresent(
      DataSourceConnectionSpec?.self, forKey: .dataSourceConnectionSpec)
    {
      try specCheckAndSet(.dataSourceConnectionSpec(dataSourceConnectionSpec))
    }
    if let routineSpec = try container.decodeIfPresent(RoutineSpec?.self, forKey: .routineSpec) {
      try specCheckAndSet(.routineSpec(routineSpec))
    }
    if let datasetSpec = try container.decodeIfPresent(DatasetSpec?.self, forKey: .datasetSpec) {
      try specCheckAndSet(.datasetSpec(datasetSpec))
    }
    if let filesetSpec = try container.decodeIfPresent(FilesetSpec?.self, forKey: .filesetSpec) {
      try specCheckAndSet(.filesetSpec(filesetSpec))
    }
    if let serviceSpec = try container.decodeIfPresent(ServiceSpec?.self, forKey: .serviceSpec) {
      try specCheckAndSet(.serviceSpec(serviceSpec))
    }
    if let modelSpec = try container.decodeIfPresent(ModelSpec?.self, forKey: .modelSpec) {
      try specCheckAndSet(.modelSpec(modelSpec))
    }
    if let featureOnlineStoreSpec = try container.decodeIfPresent(
      FeatureOnlineStoreSpec?.self, forKey: .featureOnlineStoreSpec)
    {
      try specCheckAndSet(.featureOnlineStoreSpec(featureOnlineStoreSpec))
    }
    self.spec = spec
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.linkedResource, forKey: .linkedResource)
    try container.encode(self.fullyQualifiedName, forKey: .fullyQualifiedName)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.businessContext, forKey: .businessContext)
    try container.encode(self.schema, forKey: .schema)
    try container.encode(self.sourceSystemTimestamps, forKey: .sourceSystemTimestamps)
    try container.encode(self.usageSignal, forKey: .usageSignal)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.dataSource, forKey: .dataSource)
    try container.encode(self.personalDetails, forKey: .personalDetails)

    if let choice = self.entryType {
      switch choice {
      case .type(let value):
        try container.encode(value, forKey: .type)
      case .userSpecifiedType(let value):
        try container.encode(value, forKey: .userSpecifiedType)
      }
    }

    if let choice = self.system {
      switch choice {
      case .integratedSystem(let value):
        try container.encode(value, forKey: .integratedSystem)
      case .userSpecifiedSystem(let value):
        try container.encode(value, forKey: .userSpecifiedSystem)
      }
    }

    if let choice = self.systemSpec {
      switch choice {
      case .sqlDatabaseSystemSpec(let value):
        try container.encode(value, forKey: .sqlDatabaseSystemSpec)
      case .lookerSystemSpec(let value):
        try container.encode(value, forKey: .lookerSystemSpec)
      case .cloudBigtableSystemSpec(let value):
        try container.encode(value, forKey: .cloudBigtableSystemSpec)
      }
    }

    if let choice = self.typeSpec {
      switch choice {
      case .gcsFilesetSpec(let value):
        try container.encode(value, forKey: .gcsFilesetSpec)
      case .bigqueryTableSpec(let value):
        try container.encode(value, forKey: .bigqueryTableSpec)
      case .bigqueryDateShardedSpec(let value):
        try container.encode(value, forKey: .bigqueryDateShardedSpec)
      }
    }

    if let choice = self.spec {
      switch choice {
      case .databaseTableSpec(let value):
        try container.encode(value, forKey: .databaseTableSpec)
      case .dataSourceConnectionSpec(let value):
        try container.encode(value, forKey: .dataSourceConnectionSpec)
      case .routineSpec(let value):
        try container.encode(value, forKey: .routineSpec)
      case .datasetSpec(let value):
        try container.encode(value, forKey: .datasetSpec)
      case .filesetSpec(let value):
        try container.encode(value, forKey: .filesetSpec)
      case .serviceSpec(let value):
        try container.encode(value, forKey: .serviceSpec)
      case .modelSpec(let value):
        try container.encode(value, forKey: .modelSpec)
      case .featureOnlineStoreSpec(let value):
        try container.encode(value, forKey: .featureOnlineStoreSpec)
      }
    }
  }

  /// Required. Entry type.
  public enum OneOf_EntryType: Codable, Equatable, Sendable {
    /// The type of the entry.
    ///
    /// For details, see [`EntryType`](#entrytype).
    case type(EntryType)
    /// Custom entry type that doesn't match any of the values allowed for input
    /// and listed in the `EntryType` enum.
    ///
    /// When creating an entry, first check the type values in the enum.
    /// If there are no appropriate types for the new entry,
    /// provide a custom value, for example, `my_special_type`.
    ///
    /// The `user_specified_type` string has the following limitations:
    ///
    /// * Is case insensitive.
    /// * Must begin with a letter or underscore.
    /// * Can only contain letters, numbers, and underscores.
    /// * Must be at least 1 character and at most 64 characters long.
    case userSpecifiedType(Swift.String)
  }

  /// The source system of the entry.
  public enum OneOf_System: Codable, Equatable, Sendable {
    /// Output only. Indicates the entry's source system that Data Catalog
    /// integrates with, such as BigQuery, Pub/Sub, or Dataproc Metastore.
    case integratedSystem(IntegratedSystem)
    /// Indicates the entry's source system that Data Catalog doesn't
    /// automatically integrate with.
    ///
    /// The `user_specified_system` string has the following limitations:
    ///
    /// * Is case insensitive.
    /// * Must begin with a letter or underscore.
    /// * Can only contain letters, numbers, and underscores.
    /// * Must be at least 1 character and at most 64 characters long.
    case userSpecifiedSystem(Swift.String)
  }

  /// System specification.
  /// Can be used as a complement for `spec`, when some metadata is relevant for
  /// all entries existing within given system
  public enum OneOf_SystemSpec: Codable, Equatable, Sendable {
    /// Specification that applies to a relational database system. Only settable
    /// when `user_specified_system` is equal to `SQL_DATABASE`
    indirect case sqlDatabaseSystemSpec(SqlDatabaseSystemSpec?)
    /// Specification that applies to Looker sysstem. Only settable when
    /// `user_specified_system` is equal to `LOOKER`
    indirect case lookerSystemSpec(LookerSystemSpec?)
    /// Specification that applies to Cloud Bigtable system. Only settable when
    /// `integrated_system` is equal to `CLOUD_BIGTABLE`
    indirect case cloudBigtableSystemSpec(CloudBigtableSystemSpec?)
  }

  /// Type specification.
  public enum OneOf_TypeSpec: Codable, Equatable, Sendable {
    /// Specification that applies to a Cloud Storage fileset. Valid only
    /// for entries with the `FILESET` type.
    indirect case gcsFilesetSpec(GcsFilesetSpec?)
    /// Output only. Specification that applies to a BigQuery table. Valid only
    /// for entries with the `TABLE` type.
    indirect case bigqueryTableSpec(BigQueryTableSpec?)
    /// Output only. Specification for a group of BigQuery tables with
    /// the `[prefix]YYYYMMDD` name pattern.
    ///
    /// For more information, see [Introduction to partitioned tables]
    /// (https://cloud.google.com/bigquery/docs/partitioned-tables#partitioning_versus_sharding).
    indirect case bigqueryDateShardedSpec(BigQueryDateShardedSpec?)
  }

  /// Type- and system-specific information. Specifications for types contain
  /// fields common to all entries of a given type, and sub-specifications with
  /// fields specific to a given source system.
  ///
  /// When extending the API with new types and systems, use this field instead
  /// of the legacy `type_spec`.
  public enum OneOf_Spec: Codable, Equatable, Sendable {
    /// Specification that applies to a table resource. Valid only
    /// for entries with the `TABLE` or `EXPLORE` type.
    indirect case databaseTableSpec(DatabaseTableSpec?)
    /// Specification that applies to a data source connection. Valid only
    /// for entries with the `DATA_SOURCE_CONNECTION` type.
    indirect case dataSourceConnectionSpec(DataSourceConnectionSpec?)
    /// Specification that applies to a user-defined function or procedure. Valid
    /// only for entries with the `ROUTINE` type.
    indirect case routineSpec(RoutineSpec?)
    /// Specification that applies to a dataset.
    indirect case datasetSpec(DatasetSpec?)
    /// Specification that applies to a fileset resource. Valid only
    /// for entries with the `FILESET` type.
    indirect case filesetSpec(FilesetSpec?)
    /// Specification that applies to a Service resource.
    indirect case serviceSpec(ServiceSpec?)
    /// Model specification.
    indirect case modelSpec(ModelSpec?)
    /// FeatureonlineStore spec for Vertex AI Feature Store.
    indirect case featureOnlineStoreSpec(FeatureOnlineStoreSpec?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.Entry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
