// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes a Cloud Storage fileset entry.
public struct GcsFilesetSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Patterns to identify a set of files in Google Cloud Storage.
  ///
  /// For more information, see [Wildcard Names]
  /// (https://cloud.google.com/storage/docs/wildcards).
  ///
  /// Note: Currently, bucket wildcards are not supported.
  ///
  /// Examples of valid `file_patterns`:
  ///
  ///  * `gs://bucket_name/dir/*`: matches all files in `bucket_name/dir`
  ///                              directory
  ///  * `gs://bucket_name/dir/**`: matches all files in `bucket_name/dir`
  ///                               and all subdirectories
  ///  * `gs://bucket_name/file*`: matches files prefixed by `file` in
  ///                              `bucket_name`
  ///  * `gs://bucket_name/??.txt`: matches files with two characters followed by
  ///                               `.txt` in `bucket_name`
  ///  * `gs://bucket_name/[aeiou].txt`: matches files that contain a single
  ///                                    vowel character followed by `.txt` in
  ///                                    `bucket_name`
  ///  * `gs://bucket_name/[a-m].txt`: matches files that contain `a`, `b`, ...
  ///                                  or `m` followed by `.txt` in `bucket_name`
  ///  * `gs://bucket_name/a/*/b`: matches all files in `bucket_name` that match
  ///                              the `a/*/b` pattern, such as `a/c/b`, `a/d/b`
  ///  * `gs://another_bucket/a.txt`: matches `gs://another_bucket/a.txt`
  ///
  /// You can combine wildcards to match complex sets of files, for example:
  ///
  /// `gs://bucket_name/[a-m]??.j*g`
  public var filePatterns: [Swift.String] = []

  /// Output only. Sample files contained in this fileset, not all files
  /// contained in this fileset are represented here.
  public var sampleGcsFileSpecs: [GcsFileSpec] = []

  /// Initialize a new instance of `GcsFilesetSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsFilesetSpec().with { $0.filePatterns = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.GcsFilesetSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
