// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ImportEntries][google.cloud.datacatalog.v1.DataCatalog.ImportEntries]
/// method.
///
/// [google.cloud.datacatalog.v1.DataCatalog.ImportEntries]: <doc:DataCatalogClient/importEntries(request:options:)>
public struct ImportEntriesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Target entry group for ingested entries.
  public var parent: Swift.String = Swift.String()

  /// Optional. (Optional) Dataplex task job id, if specified will be used as
  /// part of ImportEntries LRO ID
  public var jobId: Swift.String = Swift.String()

  /// Source of imported entries, e.g. dump stored in a Cloud Storage
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `ImportEntriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportEntriesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case parent = "parent"
    case gcsBucketPath = "gcsBucketPath"
    case jobId = "jobId"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.jobId = try container.decode(Swift.String.self, forKey: .jobId)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsBucketPath = try container.decodeIfPresent(Swift.String.self, forKey: .gcsBucketPath)
    {
      try sourceCheckAndSet(.gcsBucketPath(gcsBucketPath))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.jobId, forKey: .jobId)

    if let choice = self.source {
      switch choice {
      case .gcsBucketPath(let value):
        try container.encode(value, forKey: .gcsBucketPath)
      }
    }
  }

  /// Source of imported entries, e.g. dump stored in a Cloud Storage
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Path to a Cloud Storage bucket that contains a dump ready for ingestion.
    case gcsBucketPath(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.ImportEntriesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
