// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ListEntries][google.cloud.datacatalog.v1.DataCatalog.ListEntries].
///
/// [google.cloud.datacatalog.v1.DataCatalog.ListEntries]: <doc:DataCatalog/listEntries(request:)>
public struct ListEntriesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the entry group that contains the entries to list.
  ///
  /// Can be provided in URL format.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of items to return. Default is 10. Maximum limit is
  /// 1000. Throws an invalid argument if `page_size` is more than 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Pagination token that specifies the next page to return. If empty, the
  /// first page is returned.
  public var pageToken: Swift.String = Swift.String()

  /// The fields to return for each entry. If empty or omitted, all
  /// fields are returned.
  ///
  /// For example, to return a list of entries with only the `name` field,
  /// set `read_mask` to only one path with the `name` value.
  public var readMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `ListEntriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEntriesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.ListEntriesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
