// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [LookupEntry][google.cloud.datacatalog.v1.DataCatalog.LookupEntry].
///
/// [google.cloud.datacatalog.v1.DataCatalog.LookupEntry]: <doc:DataCatalogClient/lookupEntry(request:options:)>
public struct LookupEntryRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Project where the lookup should be performed. Required to lookup
  /// entry that is not a part of `DPMS` or `DATAPLEX` `integrated_system`
  /// using its `fully_qualified_name`. Ignored in other cases.
  public var project: Swift.String = Swift.String()

  /// Location where the lookup should be performed. Required to lookup
  /// entry that is not a part of `DPMS` or `DATAPLEX` `integrated_system`
  /// using its `fully_qualified_name`. Ignored in other cases.
  public var location: Swift.String = Swift.String()

  /// Required. A full name, SQL name, or a fully qualified name of a
  /// Google Cloud Platform resource.
  public var targetName: OneOf_TargetName? = nil

  /// Initialize a new instance of `LookupEntryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LookupEntryRequest().with { $0.linkedResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case linkedResource = "linkedResource"
    case sqlResource = "sqlResource"
    case fullyQualifiedName = "fullyQualifiedName"
    case project = "project"
    case location = "location"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.project = try container.decode(Swift.String.self, forKey: .project)
    self.location = try container.decode(Swift.String.self, forKey: .location)

    var targetName: OneOf_TargetName? = nil
    let targetNameCheckAndSet = {
      if targetName != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'targetName'"))
      }
      targetName = $0
    }
    if let linkedResource = try container.decodeIfPresent(
      Swift.String.self, forKey: .linkedResource)
    {
      try targetNameCheckAndSet(.linkedResource(linkedResource))
    }
    if let sqlResource = try container.decodeIfPresent(Swift.String.self, forKey: .sqlResource) {
      try targetNameCheckAndSet(.sqlResource(sqlResource))
    }
    if let fullyQualifiedName = try container.decodeIfPresent(
      Swift.String.self, forKey: .fullyQualifiedName)
    {
      try targetNameCheckAndSet(.fullyQualifiedName(fullyQualifiedName))
    }
    self.targetName = targetName
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.project, forKey: .project)
    try container.encode(self.location, forKey: .location)

    if let choice = self.targetName {
      switch choice {
      case .linkedResource(let value):
        try container.encode(value, forKey: .linkedResource)
      case .sqlResource(let value):
        try container.encode(value, forKey: .sqlResource)
      case .fullyQualifiedName(let value):
        try container.encode(value, forKey: .fullyQualifiedName)
      }
    }
  }

  /// Required. A full name, SQL name, or a fully qualified name of a
  /// Google Cloud Platform resource.
  public enum OneOf_TargetName: Codable, Equatable, Sendable {
    /// The full name of the Google Cloud Platform resource the Data Catalog
    /// entry represents. For more information, see [Full Resource Name]
    /// (https://cloud.google.com/apis/design/resource_names#full_resource_name).
    ///
    /// Full names are case-sensitive. For example:
    ///
    ///  * `//bigquery.googleapis.com/projects/{PROJECT_ID}/datasets/{DATASET_ID}/tables/{TABLE_ID}`
    ///  * `//pubsub.googleapis.com/projects/{PROJECT_ID}/topics/{TOPIC_ID}`
    case linkedResource(Swift.String)
    /// The SQL name of the entry. SQL names are case-sensitive.
    ///
    /// Examples:
    ///
    /// * `pubsub.topic.{PROJECT_ID}.{TOPIC_ID}`
    /// * `pubsub.topic.{PROJECT_ID}.`\``{TOPIC.ID.SEPARATED.WITH.DOTS}`\`
    /// * `bigquery.table.{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
    /// * `bigquery.dataset.{PROJECT_ID}.{DATASET_ID}`
    /// * `datacatalog.entry.{PROJECT_ID}.{LOCATION_ID}.{ENTRY_GROUP_ID}.{ENTRY_ID}`
    ///
    /// Identifiers (`*_ID`) should comply with the
    /// [Lexical structure in GoogleSQL]
    /// (https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical).
    case sqlResource(Swift.String)
    /// [Fully Qualified Name
    /// (FQN)](https://cloud.google.com//data-catalog/docs/fully-qualified-names)
    /// of the resource.
    ///
    /// FQNs take two forms:
    ///
    /// * For non-regionalized resources:
    ///
    ///   `{SYSTEM}:{PROJECT}.{PATH_TO_RESOURCE_SEPARATED_WITH_DOTS}`
    ///
    /// * For regionalized resources:
    ///
    ///   `{SYSTEM}:{PROJECT}.{LOCATION_ID}.{PATH_TO_RESOURCE_SEPARATED_WITH_DOTS}`
    ///
    /// Example for a DPMS table:
    ///
    /// `dataproc_metastore:{PROJECT_ID}.{LOCATION_ID}.{INSTANCE_ID}.{DATABASE_ID}.{TABLE_ID}`
    case fullyQualifiedName(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.LookupEntryRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
