// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specification that applies to
/// entries that are part `LOOKER` system
/// (user_specified_type)
public struct LookerSystemSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// ID of the parent Looker Instance. Empty if it does not exist.
  /// Example value: `someinstance.looker.com`
  public var parentInstanceId: Swift.String = Swift.String()

  /// Name of the parent Looker Instance. Empty if it does not exist.
  public var parentInstanceDisplayName: Swift.String = Swift.String()

  /// ID of the parent Model. Empty if it does not exist.
  public var parentModelId: Swift.String = Swift.String()

  /// Name of the parent Model. Empty if it does not exist.
  public var parentModelDisplayName: Swift.String = Swift.String()

  /// ID of the parent View. Empty if it does not exist.
  public var parentViewId: Swift.String = Swift.String()

  /// Name of the parent View. Empty if it does not exist.
  public var parentViewDisplayName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LookerSystemSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LookerSystemSpec().with { $0.parentInstanceId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parentInstanceId = CodingKeys(stringValue: "parentInstanceId")
    static let parentInstanceDisplayName = CodingKeys(stringValue: "parentInstanceDisplayName")
    static let parentModelId = CodingKeys(stringValue: "parentModelId")
    static let parentModelDisplayName = CodingKeys(stringValue: "parentModelDisplayName")
    static let parentViewId = CodingKeys(stringValue: "parentViewId")
    static let parentViewDisplayName = CodingKeys(stringValue: "parentViewDisplayName")

    static let _knownKeys: Set<Swift.String> = [
      "parentInstanceId",
      "parentInstanceDisplayName",
      "parentModelId",
      "parentModelDisplayName",
      "parentViewId",
      "parentViewDisplayName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentInstanceId) {
      self.parentInstanceId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .parentInstanceDisplayName)
    {
      self.parentInstanceDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentModelId) {
      self.parentModelId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentModelDisplayName)
    {
      self.parentModelDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentViewId) {
      self.parentViewId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentViewDisplayName)
    {
      self.parentViewDisplayName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parentInstanceId, forKey: .parentInstanceId)
    try container.encode(self.parentInstanceDisplayName, forKey: .parentInstanceDisplayName)
    try container.encode(self.parentModelId, forKey: .parentModelId)
    try container.encode(self.parentModelDisplayName, forKey: .parentModelDisplayName)
    try container.encode(self.parentViewId, forKey: .parentViewId)
    try container.encode(self.parentViewDisplayName, forKey: .parentViewDisplayName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.LookerSystemSpec"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
