// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specification that applies to
/// entries that are part `LOOKER` system
/// (user_specified_type)
public struct LookerSystemSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// ID of the parent Looker Instance. Empty if it does not exist.
  /// Example value: `someinstance.looker.com`
  public var parentInstanceId: Swift.String = Swift.String()

  /// Name of the parent Looker Instance. Empty if it does not exist.
  public var parentInstanceDisplayName: Swift.String = Swift.String()

  /// ID of the parent Model. Empty if it does not exist.
  public var parentModelId: Swift.String = Swift.String()

  /// Name of the parent Model. Empty if it does not exist.
  public var parentModelDisplayName: Swift.String = Swift.String()

  /// ID of the parent View. Empty if it does not exist.
  public var parentViewId: Swift.String = Swift.String()

  /// Name of the parent View. Empty if it does not exist.
  public var parentViewDisplayName: Swift.String = Swift.String()

  /// Initialize a new instance of `LookerSystemSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LookerSystemSpec().with { $0.parentInstanceId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.LookerSystemSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
