// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The configuration related to the migration to Dataplex applied to an
/// organization or project.
/// It is the response message for
/// [SetConfig][google.cloud.datacatalog.v1.DataCatalog.SetConfig] and
/// [RetrieveEffectiveConfig][google.cloud.datacatalog.v1.DataCatalog.RetrieveEffectiveConfig].
///
/// [google.cloud.datacatalog.v1.DataCatalog.RetrieveEffectiveConfig]: <doc:DataCatalogClient/retrieveEffectiveConfig(request:)>
/// [google.cloud.datacatalog.v1.DataCatalog.SetConfig]: <doc:DataCatalogClient/setConfig(request:)>
public struct MigrationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Opt-in status for the migration of Tag Templates to Dataplex.
  public var tagTemplateMigration: TagTemplateMigration = TagTemplateMigration()

  /// Opt-in status for the UI switch to Dataplex.
  public var catalogUiExperience: CatalogUIExperience = CatalogUIExperience()

  /// The time when the Tag Template migration was enabled.
  /// If the Tag Template migration is not enabled, this field is not set.
  public var templateMigrationEnabledTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `MigrationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MigrationConfig().with { $0.tagTemplateMigration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.MigrationConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
