// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Native schema used by a resource represented as an entry. Used by query
/// engines for deserializing and parsing source data.
public struct PhysicalSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var schema: OneOf_Schema? = nil

  /// Initialize a new instance of `PhysicalSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PhysicalSchema().with { $0.avro = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case avro = "avro"
    case thrift = "thrift"
    case protobuf = "protobuf"
    case parquet = "parquet"
    case orc = "orc"
    case csv = "csv"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var schema: OneOf_Schema? = nil
    let schemaCheckAndSet = {
      if schema != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'schema'"))
      }
      schema = $0
    }
    if let avro = try container.decodeIfPresent(PhysicalSchema.AvroSchema?.self, forKey: .avro) {
      try schemaCheckAndSet(.avro(avro))
    }
    if let thrift = try container.decodeIfPresent(
      PhysicalSchema.ThriftSchema?.self, forKey: .thrift)
    {
      try schemaCheckAndSet(.thrift(thrift))
    }
    if let protobuf = try container.decodeIfPresent(
      PhysicalSchema.ProtobufSchema?.self, forKey: .protobuf)
    {
      try schemaCheckAndSet(.protobuf(protobuf))
    }
    if let parquet = try container.decodeIfPresent(
      PhysicalSchema.ParquetSchema?.self, forKey: .parquet)
    {
      try schemaCheckAndSet(.parquet(parquet))
    }
    if let orc = try container.decodeIfPresent(PhysicalSchema.OrcSchema?.self, forKey: .orc) {
      try schemaCheckAndSet(.orc(orc))
    }
    if let csv = try container.decodeIfPresent(PhysicalSchema.CsvSchema?.self, forKey: .csv) {
      try schemaCheckAndSet(.csv(csv))
    }
    self.schema = schema
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.schema {
      switch choice {
      case .avro(let value):
        try container.encode(value, forKey: .avro)
      case .thrift(let value):
        try container.encode(value, forKey: .thrift)
      case .protobuf(let value):
        try container.encode(value, forKey: .protobuf)
      case .parquet(let value):
        try container.encode(value, forKey: .parquet)
      case .orc(let value):
        try container.encode(value, forKey: .orc)
      case .csv(let value):
        try container.encode(value, forKey: .csv)
      }
    }
  }

  /// Schema in Avro JSON format.
  public struct AvroSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// JSON source of the Avro schema.
    public var text: Swift.String = Swift.String()

    /// Initialize a new instance of `AvroSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AvroSchema().with { $0.text = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema.AvroSchema"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Schema in Thrift format.
  public struct ThriftSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Thrift IDL source of the schema.
    public var text: Swift.String = Swift.String()

    /// Initialize a new instance of `ThriftSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ThriftSchema().with { $0.text = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema.ThriftSchema"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Schema in protocol buffer format.
  public struct ProtobufSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Protocol buffer source of the schema.
    public var text: Swift.String = Swift.String()

    /// Initialize a new instance of `ProtobufSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProtobufSchema().with { $0.text = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema.ProtobufSchema"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Marks a Parquet-encoded data source.
  public struct ParquetSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `ParquetSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ParquetSchema().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema.ParquetSchema"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Marks an ORC-encoded data source.
  public struct OrcSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `OrcSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OrcSchema().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema.OrcSchema"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Marks a CSV-encoded data source.
  public struct CsvSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `CsvSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CsvSchema().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema.CsvSchema"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_Schema: Codable, Equatable, Sendable {
    /// Schema in Avro JSON format.
    indirect case avro(PhysicalSchema.AvroSchema?)
    /// Schema in Thrift format.
    indirect case thrift(PhysicalSchema.ThriftSchema?)
    /// Schema in protocol buffer format.
    indirect case protobuf(PhysicalSchema.ProtobufSchema?)
    /// Marks a Parquet-encoded data source.
    indirect case parquet(PhysicalSchema.ParquetSchema?)
    /// Marks an ORC-encoded data source.
    indirect case orc(PhysicalSchema.OrcSchema?)
    /// Marks a CSV-encoded data source.
    indirect case csv(PhysicalSchema.CsvSchema?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.PhysicalSchema"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
