// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax

/// Policy Tag Manager Serialization API service allows you to manipulate
/// your policy tags and taxonomies in a serialized format.
///
/// Taxonomy is a hierarchical group of policy tags.
///
/// @Snippet(path: "PolicyTagManagerSerializationQuickstart")
public class PolicyTagManagerSerializationClient: Clients.PolicyTagManagerSerializationProtocol {
  let inner: any Clients.PolicyTagManagerSerializationStub

  /// Creates a new `PolicyTagManagerSerializationClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.PolicyTagManagerSerializationStub =
      try Clients.PolicyTagManagerSerializationTransport(options)
    inner = Clients.PolicyTagManagerSerializationRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PolicyTagManagerSerializationLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Replaces (updates) a taxonomy and all its policy tags.
  ///
  /// The taxonomy and its entire hierarchy of policy tags must be
  /// represented literally by `SerializedTaxonomy` and the nested
  /// `SerializedPolicyTag` messages.
  ///
  /// This operation automatically does the following:
  ///
  /// - Deletes the existing policy tags that are missing from the
  ///   `SerializedPolicyTag`.
  /// - Creates policy tags that don't have resource names. They are considered
  ///   new.
  /// - Updates policy tags with valid resources names accordingly.
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_ReplaceTaxonomy")
  public func replaceTaxonomy(
    request: ReplaceTaxonomyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatacatalogV1.Taxonomy {
    try await self.inner.replaceTaxonomy(request: request, options: options)
  }

  /// Creates new taxonomies (including their policy tags) in a given project
  /// by importing from inlined or cross-regional sources.
  ///
  /// For a cross-regional source, new taxonomies are created by copying
  /// from a source in another region.
  ///
  /// For an inlined source, taxonomies and policy tags are created in bulk using
  /// nested protocol buffer structures.
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_ImportTaxonomies")
  public func importTaxonomies(
    request: ImportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatacatalogV1.ImportTaxonomiesResponse {
    try await self.inner.importTaxonomies(request: request, options: options)
  }

  /// Exports taxonomies in the requested type and returns them,
  /// including their policy tags. The requested taxonomies must belong to the
  /// same project.
  ///
  /// This method generates `SerializedTaxonomy` protocol buffers with nested
  /// policy tags that can be used as input for `ImportTaxonomies` calls.
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_ExportTaxonomies")
  public func exportTaxonomies(
    request: ExportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatacatalogV1.ExportTaxonomiesResponse {
    try await self.inner.exportTaxonomies(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "PolicyTagManagerSerialization_CancelOperation")
  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PolicyTagManagerSerializationClient`.
  ///
  /// To mock `PolicyTagManagerSerializationClient` change your functions to receive
  /// `some PolicyTagManagerSerializationProtocol` or `any PolicyTagManagerSerializationProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PolicyTagManagerSerializationProtocol {
    /// See `PolicyTagManagerSerializationClient.replaceTaxonomy`.
    func replaceTaxonomy(request: ReplaceTaxonomyRequest) async throws
      -> GoogleCloudDatacatalogV1.Taxonomy

    /// See `PolicyTagManagerSerializationClient.importTaxonomies`.
    func importTaxonomies(request: ImportTaxonomiesRequest) async throws
      -> GoogleCloudDatacatalogV1.ImportTaxonomiesResponse

    /// See `PolicyTagManagerSerializationClient.exportTaxonomies`.
    func exportTaxonomies(request: ExportTaxonomiesRequest) async throws
      -> GoogleCloudDatacatalogV1.ExportTaxonomiesResponse

    /// See `PolicyTagManagerSerializationClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `PolicyTagManagerSerializationClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `PolicyTagManagerSerializationClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `PolicyTagManagerSerializationClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `PolicyTagManagerSerializationClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `PolicyTagManagerSerializationClient.cancelOperation`.
    func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

    /// See `PolicyTagManagerSerializationClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `PolicyTagManagerSerializationClient.replaceTaxonomy`.
    func replaceTaxonomy(
      request: ReplaceTaxonomyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatacatalogV1.Taxonomy

    /// See `PolicyTagManagerSerializationClient.importTaxonomies`.
    func importTaxonomies(
      request: ImportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatacatalogV1.ImportTaxonomiesResponse

    /// See `PolicyTagManagerSerializationClient.exportTaxonomies`.
    func exportTaxonomies(
      request: ExportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatacatalogV1.ExportTaxonomiesResponse

    /// See `PolicyTagManagerSerializationClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `PolicyTagManagerSerializationClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `PolicyTagManagerSerializationClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `PolicyTagManagerSerializationClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.PolicyTagManagerSerializationProtocol {
  public func replaceTaxonomy(request: ReplaceTaxonomyRequest) async throws
    -> GoogleCloudDatacatalogV1.Taxonomy
  {
    try await self.replaceTaxonomy(request: request, options: .init())
  }

  public func replaceTaxonomy(
    request: ReplaceTaxonomyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatacatalogV1.Taxonomy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func importTaxonomies(request: ImportTaxonomiesRequest) async throws
    -> GoogleCloudDatacatalogV1.ImportTaxonomiesResponse
  {
    try await self.importTaxonomies(request: request, options: .init())
  }

  public func importTaxonomies(
    request: ImportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatacatalogV1.ImportTaxonomiesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func exportTaxonomies(request: ExportTaxonomiesRequest) async throws
    -> GoogleCloudDatacatalogV1.ExportTaxonomiesResponse
  {
    try await self.exportTaxonomies(request: request, options: .init())
  }

  public func exportTaxonomies(
    request: ExportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatacatalogV1.ExportTaxonomiesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
