// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class PolicyTagManagerSerializationLogging: PolicyTagManagerSerializationStub {
    let inner: any PolicyTagManagerSerializationStub
    let logger: Logger

    public init(_ inner: any PolicyTagManagerSerializationStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-datacatalog-v1"
      logger[metadataKey: "gcp.client.service"] = "datacatalog"
      logger[metadataKey: "gcp.experimental.swift.client"] = "PolicyTagManagerSerialization"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func replaceTaxonomy(
      request: ReplaceTaxonomyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Taxonomy {
      try await self._intercept(
        request: request,
        options: options,
        name: "replaceTaxonomy",
        action: {
          (r: ReplaceTaxonomyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.Taxonomy
          in
          return try await self.inner.replaceTaxonomy(request: r, options: o)
        })
    }

    public func importTaxonomies(
      request: ImportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ImportTaxonomiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "importTaxonomies",
        action: {
          (r: ImportTaxonomiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.ImportTaxonomiesResponse
          in
          return try await self.inner.importTaxonomies(request: r, options: o)
        })
    }

    public func exportTaxonomies(
      request: ExportTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ExportTaxonomiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportTaxonomies",
        action: {
          (r: ExportTaxonomiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogV1.ExportTaxonomiesResponse
          in
          return try await self.inner.exportTaxonomies(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
