// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleCloudGax

extension Clients {
  protocol PolicyTagManagerStub: Sendable {
    func createTaxonomy(
      request: CreateTaxonomyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Taxonomy

    func deleteTaxonomy(
      request: DeleteTaxonomyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updateTaxonomy(
      request: UpdateTaxonomyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Taxonomy

    func listTaxonomies(
      request: ListTaxonomiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ListTaxonomiesResponse

    func getTaxonomy(
      request: GetTaxonomyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.Taxonomy

    func createPolicyTag(
      request: CreatePolicyTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.PolicyTag

    func deletePolicyTag(
      request: DeletePolicyTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updatePolicyTag(
      request: UpdatePolicyTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.PolicyTag

    func listPolicyTags(
      request: ListPolicyTagsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.ListPolicyTagsResponse

    func getPolicyTag(
      request: GetPolicyTagRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogV1.PolicyTag

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
