// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// [Long-running operation][google.longrunning.Operation]
/// metadata message returned by the
/// [ReconcileTags][google.cloud.datacatalog.v1.DataCatalog.ReconcileTags].
///
/// [google.cloud.datacatalog.v1.DataCatalog.ReconcileTags]: <doc:DataCatalogClient/reconcileTags(request:options:)>
/// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
public struct ReconcileTagsMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// State of the reconciliation operation.
  public var state: ReconcileTagsMetadata.ReconciliationState =
    ReconcileTagsMetadata.ReconciliationState()

  /// Maps the name of each tagged column (or empty string for a
  /// sole entry) to tagging operation [status][google.rpc.Status].
  ///
  /// [google.rpc.Status]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status
  public var errors: [Swift.String: GoogleRpc.Status] = [:]

  /// Initialize a new instance of `ReconcileTagsMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReconcileTagsMetadata().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum holding possible states of the reconciliation operation.
  public enum ReconciliationState: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The reconciliation has been queued and awaits for execution.
    case reconciliationQueued
    /// The reconciliation is in progress.
    case reconciliationInProgress
    /// The reconciliation has been finished.
    case reconciliationDone
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .reconciliationQueued: return 1
      case .reconciliationInProgress: return 2
      case .reconciliationDone: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RECONCILIATION_STATE_UNSPECIFIED"
      case .reconciliationQueued: return "RECONCILIATION_QUEUED"
      case .reconciliationInProgress: return "RECONCILIATION_IN_PROGRESS"
      case .reconciliationDone: return "RECONCILIATION_DONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReconciliationState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RECONCILIATION_STATE_UNSPECIFIED": self = .unspecified
      case "RECONCILIATION_QUEUED": self = .reconciliationQueued
      case "RECONCILIATION_IN_PROGRESS": self = .reconciliationInProgress
      case "RECONCILIATION_DONE": self = .reconciliationDone
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReconciliationState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .reconciliationQueued
      case 2: self = .reconciliationInProgress
      case 3: self = .reconciliationDone
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .reconciliationQueued: return try container.encode(1)
      case .reconciliationInProgress: return try container.encode(2)
      case .reconciliationDone: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.ReconcileTagsMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
