// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ReconcileTags][google.cloud.datacatalog.v1.DataCatalog.ReconcileTags].
///
/// [google.cloud.datacatalog.v1.DataCatalog.ReconcileTags]: <doc:DataCatalogClient/reconcileTags(request:options:)>
public struct ReconcileTagsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of [Entry][google.cloud.datacatalog.v1.Entry] to be tagged.
  ///
  /// [google.cloud.datacatalog.v1.Entry]: <doc:Entry>
  public var parent: Swift.String = Swift.String()

  /// Required. The name of the tag template, which is used for reconciliation.
  public var tagTemplate: Swift.String = Swift.String()

  /// If set to `true`, deletes entry tags related to a tag template
  /// not listed in the tags source from an entry. If set to `false`,
  /// unlisted tags are retained.
  public var forceDeleteMissing: Swift.Bool = Swift.Bool()

  /// A list of tags to apply to an entry. A tag can specify a
  /// tag template, which must be the template specified in the
  /// `ReconcileTagsRequest`.
  /// The sole entry and each of its columns must be mentioned at most once.
  public var tags: [Tag] = []

  /// Initialize a new instance of `ReconcileTagsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReconcileTagsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.ReconcileTagsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
