// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// [Long-running operation][google.longrunning.Operation]
/// response message returned by
/// [ReconcileTags][google.cloud.datacatalog.v1.DataCatalog.ReconcileTags].
///
/// [google.cloud.datacatalog.v1.DataCatalog.ReconcileTags]: <doc:DataCatalogClient/reconcileTags(request:options:)>
/// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
public struct ReconcileTagsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Number of tags created in the request.
  public var createdTagsCount: Swift.Int64 = Swift.Int64()

  /// Number of tags updated in the request.
  public var updatedTagsCount: Swift.Int64 = Swift.Int64()

  /// Number of tags deleted in the request.
  public var deletedTagsCount: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReconcileTagsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReconcileTagsResponse().with { $0.createdTagsCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createdTagsCount = CodingKeys(stringValue: "createdTagsCount")
    static let updatedTagsCount = CodingKeys(stringValue: "updatedTagsCount")
    static let deletedTagsCount = CodingKeys(stringValue: "deletedTagsCount")

    static let _knownKeys: Set<Swift.String> = [
      "createdTagsCount",
      "updatedTagsCount",
      "deletedTagsCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .createdTagsCount) {
      self.createdTagsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .updatedTagsCount) {
      self.updatedTagsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .deletedTagsCount) {
      self.deletedTagsCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.createdTagsCount, forKey: .createdTagsCount)
    try container.encode(self.updatedTagsCount, forKey: .updatedTagsCount)
    try container.encode(self.deletedTagsCount, forKey: .deletedTagsCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.ReconcileTagsResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
