// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [SearchCatalog][google.cloud.datacatalog.v1.DataCatalog.SearchCatalog].
///
/// [google.cloud.datacatalog.v1.DataCatalog.SearchCatalog]: <doc:DataCatalogClient/searchCatalog(request:options:)>
public struct SearchCatalogRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The scope of this search request.
  ///
  /// The `scope` is invalid if `include_org_ids`, `include_project_ids` are
  /// empty AND `include_gcp_public_datasets` is set to `false`. In this case,
  /// the request returns an error.
  public var scope: SearchCatalogRequest.Scope? = nil

  /// Optional. The query string with a minimum of 3 characters and specific
  /// syntax. For more information, see [Data Catalog search
  /// syntax](https://cloud.google.com/data-catalog/docs/how-to/search-reference).
  ///
  /// An empty query string returns all data assets (in the specified scope)
  /// that you have access to.
  ///
  /// A query string can be a simple `xyz` or qualified by predicates:
  ///
  /// * `name:x`
  /// * `column:y`
  /// * `description:z`
  public var query: Swift.String = Swift.String()

  /// Upper bound on the number of results you can get in a single response.
  ///
  /// Can't be negative or 0, defaults to 10 in this case.
  /// The maximum number is 1000. If exceeded, throws an "invalid argument"
  /// exception.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Pagination token that, if specified, returns the next page of
  /// search results. If empty, returns the first page.
  ///
  /// This token is returned in the
  /// [SearchCatalogResponse.next_page_token][google.cloud.datacatalog.v1.SearchCatalogResponse.next_page_token]
  /// field of the response to a previous
  /// [SearchCatalogRequest][google.cloud.datacatalog.v1.DataCatalog.SearchCatalog]
  /// call.
  ///
  /// [google.cloud.datacatalog.v1.DataCatalog.SearchCatalog]: <doc:DataCatalogClient/searchCatalog(request:options:)>
  /// [google.cloud.datacatalog.v1.SearchCatalogResponse.next_page_token]: <doc:SearchCatalogResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Specifies the order of results.
  ///
  /// Currently supported case-sensitive values are:
  ///
  /// * `relevance` that can only be descending
  /// * `last_modified_timestamp [asc|desc]` with descending (`desc`) as default
  /// * `default` that can only be descending
  ///
  /// Search queries don't guarantee full recall. Results that match your query
  /// might not be returned, even in subsequent result pages. Additionally,
  /// returned (and not returned) results can vary if you repeat search queries.
  /// If you are experiencing recall issues and you don't have to fetch the
  /// results in any specific order, consider setting this parameter to
  /// `default`.
  ///
  /// If this parameter is omitted, it defaults to the descending `relevance`.
  public var orderBy: Swift.String = Swift.String()

  /// Optional. If set, use searchAll permission granted on organizations from
  /// `include_org_ids` and projects from `include_project_ids` instead of the
  /// fine grained per resource permissions when filtering the search results.
  /// The only allowed `order_by` criteria for admin_search mode is `default`.
  /// Using this flags guarantees a full recall of the search results.
  public var adminSearch: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchCatalogRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchCatalogRequest().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scope = CodingKeys(stringValue: "scope")
    static let query = CodingKeys(stringValue: "query")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let orderBy = CodingKeys(stringValue: "orderBy")
    static let adminSearch = CodingKeys(stringValue: "adminSearch")

    static let _knownKeys: Set<Swift.String> = [
      "scope",
      "query",
      "pageSize",
      "pageToken",
      "orderBy",
      "adminSearch",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scope = try container.decodeIfPresent(SearchCatalogRequest.Scope.self, forKey: .scope)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
      self.query = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .adminSearch) {
      self.adminSearch = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.scope, forKey: .scope)
    try container.encode(self.query, forKey: .query)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.orderBy, forKey: .orderBy)
    try container.encode(self.adminSearch, forKey: .adminSearch)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The criteria that select the subspace used for query matching.
  public struct Scope: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The list of organization IDs to search within.
    ///
    /// To find your organization ID, follow the steps from
    /// [Creating and managing organizations]
    /// (/resource-manager/docs/creating-managing-organization).
    public var includeOrgIds: [Swift.String] = []

    /// The list of project IDs to search within.
    ///
    /// For more information on the distinction between project names, IDs, and
    /// numbers, see [Projects](/docs/overview/#projects).
    public var includeProjectIds: [Swift.String] = []

    /// If `true`, include Google Cloud public datasets in
    /// search results. By default, they are excluded.
    ///
    /// See [Google Cloud Public Datasets](/public-datasets) for more
    /// information.
    public var includeGcpPublicDatasets: Swift.Bool = Swift.Bool()

    /// Optional. The list of locations to search within. If empty, all locations
    /// are searched.
    ///
    /// Returns an error if any location in the list isn't one of the [Supported
    /// regions](https://cloud.google.com/data-catalog/docs/concepts/regions#supported_regions).
    ///
    /// If a location is unreachable, its name is returned in the
    /// `SearchCatalogResponse.unreachable` field. To get additional information
    /// on the error, repeat the search request and set the location name as the
    /// value of this parameter.
    public var restrictedLocations: [Swift.String] = []

    /// Optional. If `true`, search only among starred entries.
    ///
    /// By default, all results are returned, starred or not.
    public var starredOnly: Swift.Bool = Swift.Bool()

    /// Optional. This field is deprecated. The search mechanism for public and
    /// private tag templates is the same.
    @available(*, deprecated)
    public var includePublicTagTemplates: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Scope`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Scope().with { $0.includeOrgIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let includeOrgIds = CodingKeys(stringValue: "includeOrgIds")
      static let includeProjectIds = CodingKeys(stringValue: "includeProjectIds")
      static let includeGcpPublicDatasets = CodingKeys(stringValue: "includeGcpPublicDatasets")
      static let restrictedLocations = CodingKeys(stringValue: "restrictedLocations")
      static let starredOnly = CodingKeys(stringValue: "starredOnly")
      static let includePublicTagTemplates = CodingKeys(stringValue: "includePublicTagTemplates")

      static let _knownKeys: Set<Swift.String> = [
        "includeOrgIds",
        "includeProjectIds",
        "includeGcpPublicDatasets",
        "restrictedLocations",
        "starredOnly",
        "includePublicTagTemplates",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includeOrgIds) {
        self.includeOrgIds = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includeProjectIds)
      {
        self.includeProjectIds = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .includeGcpPublicDatasets)
      {
        self.includeGcpPublicDatasets = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .restrictedLocations)
      {
        self.restrictedLocations = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .starredOnly) {
        self.starredOnly = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .includePublicTagTemplates)
      {
        self.includePublicTagTemplates = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.includeOrgIds, forKey: .includeOrgIds)
      try container.encode(self.includeProjectIds, forKey: .includeProjectIds)
      try container.encode(self.includeGcpPublicDatasets, forKey: .includeGcpPublicDatasets)
      try container.encode(self.restrictedLocations, forKey: .restrictedLocations)
      try container.encode(self.starredOnly, forKey: .starredOnly)
      try container.encode(self.includePublicTagTemplates, forKey: .includePublicTagTemplates)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.SearchCatalogRequest.Scope"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SearchCatalogRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
