// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [SearchCatalog][google.cloud.datacatalog.v1.DataCatalog.SearchCatalog].
///
/// [google.cloud.datacatalog.v1.DataCatalog.SearchCatalog]: <doc:DataCatalogClient/searchCatalog(request:options:)>
public struct SearchCatalogResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// Search results.
  public var results: [SearchCatalogResult] = []

  /// The approximate total number of entries matched by the query.
  public var totalSize: Swift.Int32 = Swift.Int32()

  /// Pagination token that can be used in subsequent calls to retrieve the next
  /// page of results.
  public var nextPageToken: Swift.String = Swift.String()

  /// Unreachable locations. Search results don't include data from those
  /// locations.
  ///
  /// To get additional information on an error, repeat the search request and
  /// restrict it to specific locations by setting the
  /// `SearchCatalogRequest.scope.restricted_locations` parameter.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `SearchCatalogResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchCatalogResponse().with { $0.results = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SearchCatalogResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [SearchCatalogResult] {
    return self.results
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
