// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Result in the response to a search request.
///
/// Each result captures details of one entry that matches the search.
public struct SearchCatalogResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Type of the search result.
  ///
  /// You can use this field to determine which get method to call to fetch the
  /// full resource.
  public var searchResultType: SearchResultType = SearchResultType()

  /// Sub-type of the search result.
  ///
  /// A dot-delimited full type of the resource. The same type you
  /// specify in the `type` search predicate.
  ///
  /// Examples: `entry.table`, `entry.dataStream`, `tagTemplate`.
  public var searchResultSubtype: Swift.String = Swift.String()

  /// The relative name of the resource in URL format.
  ///
  /// Examples:
  ///
  ///  * `projects/{PROJECT_ID}/locations/{LOCATION_ID}/entryGroups/{ENTRY_GROUP_ID}/entries/{ENTRY_ID}`
  ///  * `projects/{PROJECT_ID}/tagTemplates/{TAG_TEMPLATE_ID}`
  public var relativeResourceName: Swift.String = Swift.String()

  /// The full name of the Google Cloud resource the entry belongs to.
  ///
  /// For more information, see [Full Resource Name]
  /// (/apis/design/resource_names#full_resource_name).
  ///
  /// Example:
  ///
  /// `//bigquery.googleapis.com/projects/PROJECT_ID/datasets/DATASET_ID/tables/TABLE_ID`
  public var linkedResource: Swift.String = Swift.String()

  /// The last modification timestamp of the entry in the source system.
  public var modifyTime: GoogleCloudWKT.Timestamp? = nil

  /// Fully qualified name (FQN) of the resource.
  ///
  /// FQNs take two forms:
  ///
  /// * For non-regionalized resources:
  ///
  ///   `{SYSTEM}:{PROJECT}.{PATH_TO_RESOURCE_SEPARATED_WITH_DOTS}`
  ///
  /// * For regionalized resources:
  ///
  ///   `{SYSTEM}:{PROJECT}.{LOCATION_ID}.{PATH_TO_RESOURCE_SEPARATED_WITH_DOTS}`
  ///
  /// Example for a DPMS table:
  ///
  /// `dataproc_metastore:PROJECT_ID.LOCATION_ID.INSTANCE_ID.DATABASE_ID.TABLE_ID`
  public var fullyQualifiedName: Swift.String = Swift.String()

  /// The display name of the result.
  public var displayName: Swift.String = Swift.String()

  /// Entry description that can consist of several sentences or paragraphs that
  /// describe entry contents.
  public var description: Swift.String = Swift.String()

  /// The source system of the entry. Applicable only when the
  /// `search_result_type` is `ENTRY`.
  public var system: OneOf_System? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchCatalogResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchCatalogResult().with { $0.searchResultType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let searchResultType = CodingKeys(stringValue: "searchResultType")
    static let searchResultSubtype = CodingKeys(stringValue: "searchResultSubtype")
    static let relativeResourceName = CodingKeys(stringValue: "relativeResourceName")
    static let linkedResource = CodingKeys(stringValue: "linkedResource")
    static let modifyTime = CodingKeys(stringValue: "modifyTime")
    static let integratedSystem = CodingKeys(stringValue: "integratedSystem")
    static let userSpecifiedSystem = CodingKeys(stringValue: "userSpecifiedSystem")
    static let fullyQualifiedName = CodingKeys(stringValue: "fullyQualifiedName")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "searchResultType",
      "searchResultSubtype",
      "relativeResourceName",
      "linkedResource",
      "modifyTime",
      "integratedSystem",
      "userSpecifiedSystem",
      "fullyQualifiedName",
      "displayName",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(SearchResultType.self, forKey: .searchResultType) {
      self.searchResultType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .searchResultSubtype) {
      self.searchResultSubtype = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .relativeResourceName) {
      self.relativeResourceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .linkedResource) {
      self.linkedResource = value
    }
    self.modifyTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .modifyTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullyQualifiedName) {
      self.fullyQualifiedName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }

    var system: OneOf_System? = nil
    let systemCheckAndSet = {
      if system != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'system'"))
      }
      system = $0
    }
    if let integratedSystem = try container.decodeIfPresent(
      IntegratedSystem.self, forKey: .integratedSystem)
    {
      try systemCheckAndSet(.integratedSystem(integratedSystem))
    }
    if let userSpecifiedSystem = try container.decodeIfPresent(
      Swift.String.self, forKey: .userSpecifiedSystem)
    {
      try systemCheckAndSet(.userSpecifiedSystem(userSpecifiedSystem))
    }
    self.system = system
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.searchResultType, forKey: .searchResultType)
    try container.encode(self.searchResultSubtype, forKey: .searchResultSubtype)
    try container.encode(self.relativeResourceName, forKey: .relativeResourceName)
    try container.encode(self.linkedResource, forKey: .linkedResource)
    try container.encodeIfPresent(self.modifyTime, forKey: .modifyTime)
    try container.encode(self.fullyQualifiedName, forKey: .fullyQualifiedName)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)

    if let choice = self.system {
      switch choice {
      case .integratedSystem(let value):
        try container.encode(value, forKey: .integratedSystem)
      case .userSpecifiedSystem(let value):
        try container.encode(value, forKey: .userSpecifiedSystem)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The source system of the entry. Applicable only when the
  /// `search_result_type` is `ENTRY`.
  public enum OneOf_System: Codable, Equatable, Sendable {
    /// Output only. The source system that Data Catalog automatically integrates
    /// with, such as BigQuery, Cloud Pub/Sub, or Dataproc Metastore.
    case integratedSystem(IntegratedSystem)
    /// Custom source system that you can manually integrate Data Catalog with.
    case userSpecifiedSystem(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SearchCatalogResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
