// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A nested protocol buffer that represents a policy tag and all its
/// descendants.
public struct SerializedPolicyTag: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Resource name of the policy tag.
  ///
  /// This field is ignored when calling `ImportTaxonomies`.
  public var policyTag: Swift.String = Swift.String()

  /// Required. Display name of the policy tag. At most 200 bytes when encoded
  /// in UTF-8.
  public var displayName: Swift.String = Swift.String()

  /// Description of the serialized policy tag. At most
  /// 2000 bytes when encoded in UTF-8. If not set, defaults to an
  /// empty description.
  public var description: Swift.String = Swift.String()

  /// Children of the policy tag, if any.
  public var childPolicyTags: [SerializedPolicyTag] = []

  /// Initialize a new instance of `SerializedPolicyTag`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SerializedPolicyTag().with { $0.policyTag = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SerializedPolicyTag"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
