// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A nested protocol buffer that represents a taxonomy and the hierarchy of its
/// policy tags. Used for taxonomy replacement, import, and
/// export.
public struct SerializedTaxonomy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Display name of the taxonomy. At most 200 bytes when encoded in
  /// UTF-8.
  public var displayName: Swift.String = Swift.String()

  /// Description of the serialized taxonomy. At most 2000 bytes when
  /// encoded in UTF-8. If not set, defaults to an empty description.
  public var description: Swift.String = Swift.String()

  /// Top level policy tags associated with the taxonomy, if any.
  public var policyTags: [SerializedPolicyTag] = []

  /// A list of policy types that are activated per taxonomy.
  public var activatedPolicyTypes: [Taxonomy.PolicyType] = []

  /// Initialize a new instance of `SerializedTaxonomy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SerializedTaxonomy().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SerializedTaxonomy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
