// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Specification that applies to a Service resource. Valid only
/// for entries with the `SERVICE` type.
public struct ServiceSpec: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// System spec
  public var systemSpec: OneOf_SystemSpec? = nil

  /// Initialize a new instance of `ServiceSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceSpec().with { $0.cloudBigtableInstanceSpec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudBigtableInstanceSpec = "cloudBigtableInstanceSpec"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var systemSpec: OneOf_SystemSpec? = nil
    let systemSpecCheckAndSet = {
      if systemSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'systemSpec'"))
      }
      systemSpec = $0
    }
    if let cloudBigtableInstanceSpec = try container.decodeIfPresent(
      CloudBigtableInstanceSpec?.self, forKey: .cloudBigtableInstanceSpec)
    {
      try systemSpecCheckAndSet(.cloudBigtableInstanceSpec(cloudBigtableInstanceSpec))
    }
    self.systemSpec = systemSpec
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.systemSpec {
      switch choice {
      case .cloudBigtableInstanceSpec(let value):
        try container.encode(value, forKey: .cloudBigtableInstanceSpec)
      }
    }
  }

  /// System spec
  public enum OneOf_SystemSpec: Codable, Equatable, Sendable {
    /// Specification that applies to Instance entries of `CLOUD_BIGTABLE`
    /// system.
    indirect case cloudBigtableInstanceSpec(CloudBigtableInstanceSpec?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.ServiceSpec"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
