// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [SetConfig][google.cloud.datacatalog.v1.DataCatalog.SetConfig].
///
/// [google.cloud.datacatalog.v1.DataCatalog.SetConfig]: <doc:DataCatalog/setConfig(request:)>
public struct SetConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The organization or project whose config is being specified.
  public var name: Swift.String = Swift.String()

  /// The configuration field to set.
  public var configuration: OneOf_Configuration? = nil

  /// Initialize a new instance of `SetConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SetConfigRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case tagTemplateMigration = "tagTemplateMigration"
    case catalogUiExperience = "catalogUiExperience"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var configuration: OneOf_Configuration? = nil
    let configurationCheckAndSet = {
      if configuration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'configuration'"))
      }
      configuration = $0
    }
    if let tagTemplateMigration = try container.decodeIfPresent(
      TagTemplateMigration.self, forKey: .tagTemplateMigration)
    {
      try configurationCheckAndSet(.tagTemplateMigration(tagTemplateMigration))
    }
    if let catalogUiExperience = try container.decodeIfPresent(
      CatalogUIExperience.self, forKey: .catalogUiExperience)
    {
      try configurationCheckAndSet(.catalogUiExperience(catalogUiExperience))
    }
    self.configuration = configuration
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.configuration {
      switch choice {
      case .tagTemplateMigration(let value):
        try container.encode(value, forKey: .tagTemplateMigration)
      case .catalogUiExperience(let value):
        try container.encode(value, forKey: .catalogUiExperience)
      }
    }
  }

  /// The configuration field to set.
  public enum OneOf_Configuration: Codable, Equatable, Sendable {
    /// Opt-in status for the migration of Tag Templates to Dataplex.
    case tagTemplateMigration(TagTemplateMigration)
    /// Opt-in status for the UI switch to Dataplex.
    case catalogUiExperience(CatalogUIExperience)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SetConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
