// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specification that applies to
/// entries that are part `SQL_DATABASE` system
/// (user_specified_type)
public struct SqlDatabaseSystemSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// SQL Database Engine.
  /// enum SqlEngine {
  ///  UNDEFINED = 0;
  ///  MY_SQL = 1;
  ///  POSTGRE_SQL = 2;
  ///  SQL_SERVER = 3;
  /// }
  /// Engine of the enclosing database instance.
  public var sqlEngine: Swift.String = Swift.String()

  /// Version of the database engine.
  public var databaseVersion: Swift.String = Swift.String()

  /// Host of the SQL database
  /// enum InstanceHost {
  ///  UNDEFINED = 0;
  ///  SELF_HOSTED = 1;
  ///  CLOUD_SQL = 2;
  ///  AMAZON_RDS = 3;
  ///  AZURE_SQL = 4;
  /// }
  /// Host of the enclousing database instance.
  public var instanceHost: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SqlDatabaseSystemSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SqlDatabaseSystemSpec().with { $0.sqlEngine = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sqlEngine = CodingKeys(stringValue: "sqlEngine")
    static let databaseVersion = CodingKeys(stringValue: "databaseVersion")
    static let instanceHost = CodingKeys(stringValue: "instanceHost")

    static let _knownKeys: Set<Swift.String> = [
      "sqlEngine",
      "databaseVersion",
      "instanceHost",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sqlEngine) {
      self.sqlEngine = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .databaseVersion) {
      self.databaseVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceHost) {
      self.instanceHost = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sqlEngine, forKey: .sqlEngine)
    try container.encode(self.databaseVersion, forKey: .databaseVersion)
    try container.encode(self.instanceHost, forKey: .instanceHost)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.SqlDatabaseSystemSpec"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
