// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Table source type.
public enum TableSourceType: Codable, Equatable, Sendable {
  /// Default unknown type.
  case unspecified
  /// Table view.
  case bigqueryView
  /// BigQuery native table.
  case bigqueryTable
  /// BigQuery materialized view.
  case bigqueryMaterializedView
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .bigqueryView: return 2
    case .bigqueryTable: return 5
    case .bigqueryMaterializedView: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "TABLE_SOURCE_TYPE_UNSPECIFIED"
    case .bigqueryView: return "BIGQUERY_VIEW"
    case .bigqueryTable: return "BIGQUERY_TABLE"
    case .bigqueryMaterializedView: return "BIGQUERY_MATERIALIZED_VIEW"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TableSourceType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "TABLE_SOURCE_TYPE_UNSPECIFIED": self = .unspecified
    case "BIGQUERY_VIEW": self = .bigqueryView
    case "BIGQUERY_TABLE": self = .bigqueryTable
    case "BIGQUERY_MATERIALIZED_VIEW": self = .bigqueryMaterializedView
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TableSourceType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 2: self = .bigqueryView
    case 5: self = .bigqueryTable
    case 7: self = .bigqueryMaterializedView
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .bigqueryView: return try container.encode(2)
    case .bigqueryTable: return try container.encode(5)
    case .bigqueryMaterializedView: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
