// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Contains the value and additional information on a field within
/// a [Tag][google.cloud.datacatalog.v1.Tag].
///
/// [google.cloud.datacatalog.v1.Tag]: <doc:Tag>
public struct TagField: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The display name of this field.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The order of this field with respect to other fields in this
  /// tag. Can be set by
  /// [Tag][google.cloud.datacatalog.v1.TagTemplateField.order].
  ///
  /// For example, a higher value can indicate a more important field.
  /// The value can be negative. Multiple fields can have the same order, and
  /// field orders within a tag don't have to be sequential.
  ///
  /// [google.cloud.datacatalog.v1.TagTemplateField.order]: <doc:TagTemplateField/order>
  public var order: Swift.Int32 = Swift.Int32()

  /// Required. The value of this field.
  public var kind: KindOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TagField`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TagField().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let displayName = CodingKeys(stringValue: "displayName")
    static let doubleValue = CodingKeys(stringValue: "doubleValue")
    static let stringValue = CodingKeys(stringValue: "stringValue")
    static let boolValue = CodingKeys(stringValue: "boolValue")
    static let timestampValue = CodingKeys(stringValue: "timestampValue")
    static let enumValue = CodingKeys(stringValue: "enumValue")
    static let richtextValue = CodingKeys(stringValue: "richtextValue")
    static let order = CodingKeys(stringValue: "order")

    static let _knownKeys: Set<Swift.String> = [
      "displayName",
      "doubleValue",
      "stringValue",
      "boolValue",
      "timestampValue",
      "enumValue",
      "richtextValue",
      "order",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .order) {
      self.order = value
    }

    var kind: KindOneOf? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let doubleValue = try container.decodeIfPresent(Swift.Double.self, forKey: .doubleValue) {
      try kindCheckAndSet(.doubleValue(doubleValue))
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try kindCheckAndSet(.stringValue(stringValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try kindCheckAndSet(.boolValue(boolValue))
    }
    if let timestampValue = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp?.self, forKey: .timestampValue)
    {
      try kindCheckAndSet(.timestampValue(timestampValue))
    }
    if let enumValue = try container.decodeIfPresent(TagField.EnumValue?.self, forKey: .enumValue) {
      try kindCheckAndSet(.enumValue(enumValue))
    }
    if let richtextValue = try container.decodeIfPresent(Swift.String.self, forKey: .richtextValue)
    {
      try kindCheckAndSet(.richtextValue(richtextValue))
    }
    self.kind = kind
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.order, forKey: .order)

    if let choice = self.kind {
      switch choice {
      case .doubleValue(let value):
        try container.encode(value, forKey: .doubleValue)
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .timestampValue(let value):
        try container.encode(value, forKey: .timestampValue)
      case .enumValue(let value):
        try container.encode(value, forKey: .enumValue)
      case .richtextValue(let value):
        try container.encode(value, forKey: .richtextValue)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// An enum value.
  public struct EnumValue: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The display name of the enum value.
    public var displayName: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EnumValue`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EnumValue().with { $0.displayName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let displayName = CodingKeys(stringValue: "displayName")

      static let _knownKeys: Set<Swift.String> = [
        "displayName"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.displayName, forKey: .displayName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.v1.TagField.EnumValue"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Required. The value of this field.
  public enum KindOneOf: Codable, Equatable, Sendable {
    /// The value of a tag field with a double type.
    case doubleValue(Swift.Double)
    /// The value of a tag field with a string type.
    ///
    /// The maximum length is 2000 UTF-8 characters.
    case stringValue(Swift.String)
    /// The value of a tag field with a boolean type.
    case boolValue(Swift.Bool)
    /// The value of a tag field with a timestamp type.
    indirect case timestampValue(GoogleWKT.WKTTimestamp?)
    /// The value of a tag field with an enum type.
    ///
    /// This value must be one of the allowed values listed in this enum.
    indirect case enumValue(TagField.EnumValue?)
    /// The value of a tag field with a rich text type.
    ///
    /// The maximum length is 10 MiB as this value holds HTML descriptions
    /// including encoded images. The maximum length of the text without images
    /// is 100 KiB.
    case richtextValue(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.TagField"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
