// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The template for an individual field within a tag template.
public struct TagTemplateField: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the tag template field in URL format.
  /// Example:
  ///
  /// `projects/{PROJECT_ID}/locations/{LOCATION}/tagTemplates/{TAG_TEMPLATE}/fields/{FIELD}`
  ///
  /// Note: The tag template field itself might not be stored in the location
  /// specified in its name.
  ///
  /// The name must contain only letters (a-z, A-Z), numbers (0-9),
  /// or underscores (_), and must start with a letter or underscore.
  /// The maximum length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// The display name for this field. Defaults to an empty string.
  ///
  /// The name must contain only Unicode letters, numbers (0-9), underscores (_),
  /// dashes (-), spaces ( ), and can't start or end with spaces.
  /// The maximum length is 200 characters.
  public var displayName: Swift.String = Swift.String()

  /// Required. The type of value this tag field can contain.
  public var type: FieldType? = nil

  /// If true, this field is required. Defaults to false.
  public var isRequired: Swift.Bool = Swift.Bool()

  /// The description for this field. Defaults to an empty string.
  public var description: Swift.String = Swift.String()

  /// The order of this field with respect to other fields in this tag
  /// template.
  ///
  /// For example, a higher value can indicate a more important field.
  /// The value can be negative. Multiple fields can have the same order and
  /// field orders within a tag don't have to be sequential.
  public var order: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `TagTemplateField`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TagTemplateField().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.TagTemplateField"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
