// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The template for an individual field within a tag template.
public struct TagTemplateField: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the tag template field in URL format.
  /// Example:
  ///
  /// `projects/{PROJECT_ID}/locations/{LOCATION}/tagTemplates/{TAG_TEMPLATE}/fields/{FIELD}`
  ///
  /// Note: The tag template field itself might not be stored in the location
  /// specified in its name.
  ///
  /// The name must contain only letters (a-z, A-Z), numbers (0-9),
  /// or underscores (_), and must start with a letter or underscore.
  /// The maximum length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// The display name for this field. Defaults to an empty string.
  ///
  /// The name must contain only Unicode letters, numbers (0-9), underscores (_),
  /// dashes (-), spaces ( ), and can't start or end with spaces.
  /// The maximum length is 200 characters.
  public var displayName: Swift.String = Swift.String()

  /// Required. The type of value this tag field can contain.
  public var type: FieldType? = nil

  /// If true, this field is required. Defaults to false.
  public var isRequired: Swift.Bool = Swift.Bool()

  /// The description for this field. Defaults to an empty string.
  public var description: Swift.String = Swift.String()

  /// The order of this field with respect to other fields in this tag
  /// template.
  ///
  /// For example, a higher value can indicate a more important field.
  /// The value can be negative. Multiple fields can have the same order and
  /// field orders within a tag don't have to be sequential.
  public var order: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TagTemplateField`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TagTemplateField().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let type = CodingKeys(stringValue: "type")
    static let isRequired = CodingKeys(stringValue: "isRequired")
    static let description = CodingKeys(stringValue: "description")
    static let order = CodingKeys(stringValue: "order")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "type",
      "isRequired",
      "description",
      "order",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.type = try container.decodeIfPresent(FieldType.self, forKey: .type)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isRequired) {
      self.isRequired = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .order) {
      self.order = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.type, forKey: .type)
    try container.encode(self.isRequired, forKey: .isRequired)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.order, forKey: .order)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.TagTemplateField"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
