// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A tag template defines a tag that can have one or more typed fields.
///
/// The template is used to create tags that are attached to Google Cloud
///  resources. [Tag template roles]
/// (https://cloud.google.com/iam/docs/understanding-roles#data-catalog-roles)
/// provide permissions to create, edit, and use the template. For example,
/// see the [TagTemplate User]
/// (https://cloud.google.com/data-catalog/docs/how-to/template-user) role
/// that includes a permission to use the tag template to tag resources.
public struct TagTemplate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the tag template in URL format.
  ///
  /// Note: The tag template itself and its child resources might not be
  /// stored in the location specified in its name.
  public var name: Swift.String = Swift.String()

  /// Display name for this template. Defaults to an empty string.
  ///
  /// The name must contain only Unicode letters, numbers (0-9), underscores (_),
  /// dashes (-), spaces ( ), and can't start or end with spaces.
  /// The maximum length is 200 characters.
  public var displayName: Swift.String = Swift.String()

  /// Indicates whether tags created with this template are public. Public tags
  /// do not require tag template access to appear in
  /// [ListTags][google.cloud.datacatalog.v1.DataCatalog.ListTags] API response.
  ///
  /// Additionally, you can search for a public tag by value with a
  /// simple search query in addition to using a ``tag:`` predicate.
  ///
  /// [google.cloud.datacatalog.v1.DataCatalog.ListTags]: <doc:DataCatalog/listTags(request:)>
  public var isPubliclyReadable: Swift.Bool = Swift.Bool()

  /// Required. Map of tag template field IDs to the settings for the field.
  /// This map is an exhaustive list of the allowed fields. The map must contain
  /// at least one field and at most 500 fields.
  ///
  /// The keys to this map are tag template field IDs. The IDs have the
  /// following limitations:
  ///
  /// * Can contain uppercase and lowercase letters, numbers (0-9) and
  ///   underscores (_).
  /// * Must be at least 1 character and at most 64 characters long.
  /// * Must start with a letter or underscore.
  public var fields: [Swift.String: TagTemplateField] = [:]

  /// Optional. Transfer status of the TagTemplate
  public var dataplexTransferStatus: TagTemplate.DataplexTransferStatus =
    TagTemplate.DataplexTransferStatus()

  /// Initialize a new instance of `TagTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TagTemplate().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// This enum describes TagTemplate transfer status to Dataplex service.
  public enum DataplexTransferStatus: Codable, Equatable, Sendable {
    /// Default value. TagTemplate and its tags are only visible and editable in
    /// DataCatalog.
    case unspecified
    /// TagTemplate and its tags are auto-copied to Dataplex service.
    /// Visible in both services. Editable in DataCatalog, read-only in Dataplex.
    /// Deprecated: Individual TagTemplate migration is deprecated in favor of
    /// organization or project wide TagTemplate migration opt-in.
    @available(*, deprecated)
    case migrated
    /// TagTemplate and its tags are auto-copied to Dataplex service.
    /// Visible in both services. Editable in Dataplex, read-only in DataCatalog.
    case transferred
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .migrated: return 1
      case .transferred: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATAPLEX_TRANSFER_STATUS_UNSPECIFIED"
      case .migrated: return "MIGRATED"
      case .transferred: return "TRANSFERRED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataplexTransferStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATAPLEX_TRANSFER_STATUS_UNSPECIFIED": self = .unspecified
      case "MIGRATED": self = .migrated
      case "TRANSFERRED": self = .transferred
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataplexTransferStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .migrated
      case 2: self = .transferred
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .migrated: return try container.encode(1)
      case .transferred: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.TagTemplate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
