// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [UpdateEntry][google.cloud.datacatalog.v1.DataCatalog.UpdateEntry].
///
/// [google.cloud.datacatalog.v1.DataCatalog.UpdateEntry]: <doc:DataCatalogClient/updateEntry(request:)>
public struct UpdateEntryRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Updates for the entry. The `name` field must be set.
  public var entry: Entry? = nil

  /// Names of fields whose values to overwrite on an entry.
  ///
  /// If this parameter is absent or empty, all modifiable fields
  /// are overwritten. If such fields are non-required and omitted in the
  /// request body, their values are emptied.
  ///
  /// You can modify only the fields listed below.
  ///
  /// For entries with type `DATA_STREAM`:
  ///
  /// * `schema`
  ///
  /// For entries with type `FILESET`:
  ///
  /// * `schema`
  /// * `display_name`
  /// * `description`
  /// * `gcs_fileset_spec`
  /// * `gcs_fileset_spec.file_patterns`
  ///
  /// For entries with `user_specified_type`:
  ///
  /// * `schema`
  /// * `display_name`
  /// * `description`
  /// * `user_specified_type`
  /// * `user_specified_system`
  /// * `linked_resource`
  /// * `source_system_timestamps`
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateEntryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateEntryRequest().with { $0.entry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.UpdateEntryRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
