// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Detail description of the source information of a Vertex model.
public struct VertexModelSourceInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Type of the model source.
  public var sourceType: VertexModelSourceInfo.ModelSourceType =
    VertexModelSourceInfo.ModelSourceType()

  /// If this Model is copy of another Model. If true then
  /// [source_type][google.cloud.datacatalog.v1.VertexModelSourceInfo.source_type]
  /// pertains to the original.
  ///
  /// [google.cloud.datacatalog.v1.VertexModelSourceInfo.source_type]: <doc:VertexModelSourceInfo/sourceType>
  public var copy: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `VertexModelSourceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VertexModelSourceInfo().with { $0.sourceType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Source of the model.
  public enum ModelSourceType: Codable, Equatable, Sendable {
    /// Should not be used.
    case unspecified
    /// The Model is uploaded by automl training pipeline.
    case automl
    /// The Model is uploaded by user or custom training pipeline.
    case custom
    /// The Model is registered and sync'ed from BigQuery ML.
    case bqml
    /// The Model is saved or tuned from Model Garden.
    case modelGarden
    /// The Model is saved or tuned from Genie.
    case genie
    /// The Model is uploaded by text embedding finetuning pipeline.
    case customTextEmbedding
    /// The Model is saved or tuned from Marketplace.
    case marketplace
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .automl: return 1
      case .custom: return 2
      case .bqml: return 3
      case .modelGarden: return 4
      case .genie: return 5
      case .customTextEmbedding: return 6
      case .marketplace: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODEL_SOURCE_TYPE_UNSPECIFIED"
      case .automl: return "AUTOML"
      case .custom: return "CUSTOM"
      case .bqml: return "BQML"
      case .modelGarden: return "MODEL_GARDEN"
      case .genie: return "GENIE"
      case .customTextEmbedding: return "CUSTOM_TEXT_EMBEDDING"
      case .marketplace: return "MARKETPLACE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModelSourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODEL_SOURCE_TYPE_UNSPECIFIED": self = .unspecified
      case "AUTOML": self = .automl
      case "CUSTOM": self = .custom
      case "BQML": self = .bqml
      case "MODEL_GARDEN": self = .modelGarden
      case "GENIE": self = .genie
      case "CUSTOM_TEXT_EMBEDDING": self = .customTextEmbedding
      case "MARKETPLACE": self = .marketplace
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModelSourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .automl
      case 2: self = .custom
      case 3: self = .bqml
      case 4: self = .modelGarden
      case 5: self = .genie
      case 6: self = .customTextEmbedding
      case 7: self = .marketplace
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .automl: return try container.encode(1)
      case .custom: return try container.encode(2)
      case .bqml: return try container.encode(3)
      case .modelGarden: return try container.encode(4)
      case .genie: return try container.encode(5)
      case .customTextEmbedding: return try container.encode(6)
      case .marketplace: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.VertexModelSourceInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
