// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Specification for vertex model resources.
public struct VertexModelSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The version ID of the model.
  public var versionId: Swift.String = Swift.String()

  /// User provided version aliases so that a model version can be referenced via
  /// alias
  public var versionAliases: [Swift.String] = []

  /// The description of this version.
  public var versionDescription: Swift.String = Swift.String()

  /// Source of a Vertex model.
  public var vertexModelSourceInfo: VertexModelSourceInfo? = nil

  /// URI of the Docker image to be used as the custom container for serving
  /// predictions.
  public var containerImageUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VertexModelSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VertexModelSpec().with { $0.versionId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let versionId = CodingKeys(stringValue: "versionId")
    static let versionAliases = CodingKeys(stringValue: "versionAliases")
    static let versionDescription = CodingKeys(stringValue: "versionDescription")
    static let vertexModelSourceInfo = CodingKeys(stringValue: "vertexModelSourceInfo")
    static let containerImageUri = CodingKeys(stringValue: "containerImageUri")

    static let _knownKeys: Set<Swift.String> = [
      "versionId",
      "versionAliases",
      "versionDescription",
      "vertexModelSourceInfo",
      "containerImageUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .versionId) {
      self.versionId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .versionAliases) {
      self.versionAliases = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .versionDescription) {
      self.versionDescription = value
    }
    self.vertexModelSourceInfo = try container.decodeIfPresent(
      VertexModelSourceInfo.self, forKey: .vertexModelSourceInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .containerImageUri) {
      self.containerImageUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.versionId, forKey: .versionId)
    try container.encode(self.versionAliases, forKey: .versionAliases)
    try container.encode(self.versionDescription, forKey: .versionDescription)
    try container.encodeIfPresent(self.vertexModelSourceInfo, forKey: .vertexModelSourceInfo)
    try container.encode(self.containerImageUri, forKey: .containerImageUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.v1.VertexModelSpec"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
